Repository devtron-labs/devtron, pull requests merged in 2022-07, with the labels that each got.

#1601 feat: Kube capacity support
  688
  api/restHandler/common/apiError.go
  api/router/router.go
  cmd/external-app/router.go
  cmd/external-app/wire_gen.go
  go.mod
  go.sum
  pkg/cluster/ClusterService.go
  pkg/cluster/repository/ClusterRepository.go
  scripts/sql/58_alter_cluster.down.sql
  scripts/sql/58_alter_cluster.up.sql
  specs/kube-capacity.yaml
  util/k8s/ClusterCronService.go
  util/k8s/bean.go
  util/k8s/k8sApplicationService.go
  util/k8s/k8sCapacityRestHandler.go
  util/k8s/k8sCapacityRouter.go
  util/k8s/k8sCapacityService.go
  util/k8s/wire_k8sApp.go
  vendor/k8s.io/metrics/LICENSE
  vendor/k8s.io/metrics/pkg/apis/metrics/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1alpha1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.pb.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.proto
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/register.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/types.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/metrics/pkg/apis/metrics/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/apis/metrics/zz_generated.deepcopy.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/clientset.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/scheme/register.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1alpha1/podmetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/doc.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/generated_expansion.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/metrics_client.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/nodemetrics.go
  vendor/k8s.io/metrics/pkg/client/clientset/versioned/typed/metrics/v1beta1/podmetrics.go
  vendor/modules.txt
  wire_gen.go
Labels: enhancement

#1977 Casbin auth data cached
  api/cluster/ClusterRestHandler.go
  api/cluster/EnvironmentRestHandler.go
  api/restHandler/AppListingRestHandler.go
  api/team/TeamRestHandler.go
  pkg/user/casbin/Adapter.go
  pkg/user/casbin/rbac.go
  pkg/user/casbin/rbacpolicy.go
Labels: bug, enhancement

#1960 Logs secret data obfuscation
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  internal/util/GitCliUtil.go
  pkg/sql/connection.go
  pkg/sql/connection_test.go
Labels: enhancement

#2031 Enforcer Rbac email case sensitive fix
  pkg/user/casbin/rbac.go
Labels: bug

#2061 1377 buildx support in ci pipelines
  api/appbean/AppDetail.go
  api/restHandler/CoreAppRestHandler.go
  internal/sql/repository/pipelineConfig/CiTemplateRepository.go
  pkg/appClone/AppCloneService.go
  pkg/bean/app.go
  pkg/pipeline/CiService.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/WorkflowService.go
  scripts/sql/61_alter_ci_template.down.sql
  scripts/sql/61_alter_ci_template.up.sql
  specs/app_create_api.yaml
Labels: enhancement

#2078 Enforcer cache For all the remaining APIs
  App.go
  pkg/user/casbin/Adapter.go
  pkg/user/casbin/rbac.go
  pkg/user/casbin/rbac_test.go
  pkg/user/casbin/rbacpolicy.go
Labels: Task

#2103 Enforcer email lowercase fix
  pkg/user/casbin/rbac.go
Labels: bug
