Repository devtron-labs/devtron, pull requests merged in 2023-09, with the labels that each got.

#3849 chore: Update pr-issue-validator.yaml
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#3763 feat: Maintaining audit logs
  App.go
  Wire.go
  api/appStore/deployment/AppStoreDeploymentRouter.go
  api/dashboardEvent/DashboardTelemetryRouter.go
  api/deployment/DeploymentConfigRouter.go
  api/helm-app/HelmAppRouter.go
  api/k8s/application/k8sApplicationRouter.go
  api/k8s/capacity/k8sCapacityRouter.go
  api/router/ApplicationRouter.go
  api/router/CommonRouter.go
  api/router/ConfigMapRouter.go
  api/router/MigrateDbRouter.go
  api/router/PProfRouter.go
  api/router/PipelineConfigRouter.go
  api/router/router.go
  api/util/logger.go
  cmd/external-app/router.go
  go.mod
  go.sum
  internal/middleware/delegator.go
  internal/middleware/instrument.go
  internal/sql/repository/appStatus/tests/AppStatusRepository_test.go
  util/mocks/rbac/EnforcerUtil.go
  vendor/github.com/google/wire/.travis.yml
  vendor/github.com/google/wire/README.md
  vendor/github.com/google/wire/wire.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#3852 fix: Makefile correction
  Makefile
  cmd/external-app/Makefile
Labels: PR:Ready-to-Review

#3862 fix: cloning app cmcs global boolean value fix
  pkg/pipeline/ConfigMapService.go
Labels: pager-duty, PR:Ready-to-Review

#3801 feat: custom chart download
  api/deployment/DeploymentConfigRestHandler.go
  api/deployment/DeploymentConfigRouter.go
  api/restHandler/common/ApiResponseErrorMapping.go
  api/restHandler/common/ApiResponseWriter.go
  api/restHandler/common/apiError.go
  internal/constants/InternalErrorCode.go
  internal/util/ChartService.go
  pkg/app/AppService.go
  pkg/chart/ChartCompatibility.go
  pkg/chart/ChartService.go
  pkg/chart/ChartUtils.go
  pkg/chart/bean.go
  pkg/chartRepo/repository/ChartRefRepository.go
Labels: enhancement, PR:Ready-to-Review

#3870 fix: migration script for virtual cluster v3
  scripts/sql/168_virtual_cluster_v3.down.sql
  scripts/sql/168_virtual_cluster_v3.up.sql
Labels: enhancement, PR:Ready-to-Review

#3842 feat: added validation for create app workflow API
  api/appbean/AppDetail.go
  api/restHandler/CoreAppRestHandler.go
  internal/sql/repository/pipelineConfig/MaterialRepository.go
  wire_gen.go
Labels: enhancement, PR:Ready-to-Review

#3811 feat: deployment history release not found err handling
  api/helm-app/applicationClient.go
  api/helm-app/bean.go
  internal/constants/InternalErrorCode.go
  internal/util/ErrorUtil.go
Labels: enhancement, PR:Ready-to-Review

#3877 fix: ci pip status query optmization
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
Labels: PR:Ready-to-Review

#3873 fix: Helm app deployment history page breaking due to user details not found
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
Labels: enhancement, PR:Ready-to-Review

#3879 chore: adjust duplicate action threshold
  .github/workflows/azure-devops-issue-sync.yml
Labels: PR:Ready-to-Review

#3876 doc: Okta SSO Configuration Doc
  docs/SUMMARY.md
  docs/user-guide/global-configurations/okta.md
Labels: PR:Ready-to-Review

#3767 fix: rbac-modification for cluster list
  api/cluster/ClusterRestHandler.go
  api/cluster/wire_cluster.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/k8s/application/k8sApplicationRouter.go
  api/k8s/capacity/k8sCapacityRestHandler.go
  cmd/external-app/wire_gen.go
  pkg/cluster/ClusterRbacService.go
  pkg/cluster/ClusterService.go
  pkg/k8s/application/k8sApplicationService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#3890 doc: draft version of Graviton benchmark
  docs/SUMMARY.md
  docs/reference/graviton.md
Labels: PR:Ready-to-Review

#3897 fix:Image tag not propagated in Rollback
  api/restHandler/app/DeploymentPipelineRestHandler.go
  pkg/pipeline/PipelineBuilder.go
Labels: PR:Issue-verification-failed

#3888 fix: block trigger for vulnerable image
  pkg/pipeline/WorkflowDagExecutor.go
Labels: enhancement, PR:Issue-verification-failed

#3880 fix: invalid post deployment status in App group
  pkg/pipeline/CdHandler.go
Labels: enhancement, PR:Ready-to-Review

#3889 fixed: updated invalid installed version error message
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
Labels: enhancement, PR:Issue-verification-failed

#3894 feat: updated error message for installed app
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
Labels: enhancement, PR:Issue-verification-failed

#3896 fix: Deployment is breaking due to invalid environment name
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/cluster/EnvironmentUtil.go
Labels: PR:Issue-verification-failed

#3905 feat: added configurable provenance flag for buildx builds
  pkg/pipeline/CiConfig.go
  pkg/pipeline/CiService.go
  pkg/pipeline/bean/CiBuildConfig.go
Labels: PR:Ready-to-Review

#3919 chore: changes for migration no conflict
  scripts/sql/170_scoped_variable.down.sql
  scripts/sql/170_scoped_variable.up.sql
Labels: PR:Ready-to-Review

#3898 fix: invalid cluster details fetched for partial delete state
  api/cluster/EnvironmentRestHandler.go
Labels: enhancement, PR:Issue-verification-failed

#3820 doc: Glossary of jargonish terms for layman in the context of Devtron
  docs/SUMMARY.md
  docs/reference/glossary.md
Labels: PR:Ready-to-Review

#3923 fix: revert app and workflow creation in case of error
  api/restHandler/CoreAppRestHandler.go
Labels: PR:Issue-verification-failed

#3939 fix: updated previous deployment status
  pkg/pipeline/WorkflowDagExecutor.go
Labels: enhancement

#3941 feat: updated delete installed app error message
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
Labels: enhancement, PR:Issue-verification-failed

#3947 fix: workflow not created for auto trigger
  pkg/pipeline/WorkflowDagExecutor.go
Labels: enhancement

#3949 fix: helm app delete error
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
Labels: enhancement

#3856 feat: Helm async install
  api/appStore/InstalledAppRestHandler.go
  api/bean/AppView.go
  api/helm-app/applist.pb.go
  api/helm-app/applist.proto
  api/helm-app/applist_grpc.pb.go
  api/restHandler/AppListingRestHandler.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  go.mod
  go.sum
  pkg/appStore/bean/bean.go
  pkg/appStore/deployment/repository/InstalledAppRepository.go
  pkg/appStore/deployment/repository/InstalledAppVersionHistory.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  scripts/sql/171_helm_async_install.down.sql
  scripts/sql/171_helm_async_install.up.sql
  util/k8s/K8sUtil.go
  util/mocks/rbac/EnforcerUtil.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/AwsS3Blob.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/BlobStorageService.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#3953 chore: added log config for dev mode
  internal/util/BasicProviders.go
Labels: PR:Ready-to-Review

#3951 feat: handle CI success event auto trigger in batch
  pkg/pipeline/CiConfig.go
  pkg/pipeline/WebhookService.go
  wire_gen.go
Labels: enhancement, PR:Ready-to-Review

#3940 fix: Base configmap get more precedence than override
  api/bean/ConfigMapAndSecret.go
  internal/util/MergeUtil.go
  util/TypeUtils.go
Labels: PR:Ready-to-Review

#3912 docs: Ephemeral Container Doc
  docs/SUMMARY.md
  docs/user-guide/app-details/ephemeral-containers.md
Labels: PR:Ready-to-Review

#3959 docs: New Image Alignment in Ephemeral doc
  docs/user-guide/app-details/ephemeral-containers.md
Labels: PR:Ready-to-Review

#3956 feat: added env variable to skip gitops validation on create/update
  pkg/app/AppService.go
  pkg/gitops/GitOpsConfigService.go
  util/GlobalConfig.go
  wire_gen.go
Labels: enhancement, PR:Ready-to-Review

#3960 feat: removed virtual environments from unnecessary places
  api/k8s/capacity/k8sCapacityRestHandler.go
  pkg/cluster/ClusterCronService.go
  pkg/cluster/ClusterService.go
  pkg/cluster/ClusterServiceExtended.go
  pkg/cluster/repository/ClusterRepository.go
  pkg/k8s/capacity/bean/bean.go
  pkg/k8s/capacity/k8sCapacityService.go
Labels: enhancement

#3963 feat: added flag to configure ecr repo creation
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CiConfig.go
Labels: PR:Ready-to-Review

#3964 docs: Snapshot updation in PVC docs + PreBuild CI-CD
  docs/user-guide/creating-application/overview.md
  docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
Labels: PR:Ready-to-Review

#3714 chore: workflow refactoring
  Wire.go
  api/restHandler/PubSubClientRestHandler.go
  api/router/pubsub/CiEventHandler.go
  api/router/router.go
  pkg/pipeline/ArgoWorkflowExecutor.go
  pkg/pipeline/ArgoWorkflowExecutor_test.go
  pkg/pipeline/CdConfig.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CdWorkflowService.go
  pkg/pipeline/CiCdConfig.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CiCdPipelineOrchestrator_test.go
  pkg/pipeline/CiConfig.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/PipelineStageService.go
  pkg/pipeline/SystemWorkflowExecutor.go
  pkg/pipeline/SystemWorkflowExecutor_test.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/WorkflowServiceIT_test.go
  pkg/pipeline/WorkflowUtils.go
  pkg/pipeline/bean/WorkflowTemplate.go
  pkg/pipeline/bean/workFlowRequestBean.go
  pkg/security/policyService.go
  util/mocks/rbac/EnforcerUtil.go
  wire_gen.go
Labels: PR:Ready-to-Review

#3967 chore: pr-issue-validator permissions fix
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#3962 fix: DT19-v1 bug fixes
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/cluster/EnvironmentRestHandler.go
  api/restHandler/ChartGroupRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
  pkg/app/AppService.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/cluster/EnvironmentUtil.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/security/ImageScanService.go
Labels: enhancement, PR:Ready-to-Review

#3911 feat: Variables support in pre-post CI, CD and Jobs
  api/bean/ValuesOverrideRequest.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/chart/ChartService.go
  pkg/chartRepo/repository/mocks/ChartRepoRepository.go
  pkg/cluster/EnvironmentService.go
  pkg/pipeline/CiCdPipelineOrchestrator_test.go
  pkg/pipeline/CiService.go
  pkg/pipeline/ConfigMapService_test.go
  pkg/pipeline/GitopsOrHelmOption_test.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/PipelineStageService.go
  pkg/pipeline/PipelineStageServiceIT_test.go
  pkg/pipeline/PropertiesConfig.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/WorkflowService_test.go
  pkg/pipeline/bean/workFlowRequestBean.go
  pkg/variables/VariableEntityMappingService.go
  pkg/variables/repository/ScopedVariableRepository.go
  pkg/variables/repository/VariableEntityDTO.go
  pkg/variables/repository/VariableEntityMappingRepository.go
  pkg/variables/repository/VariableSnapshotHistoryDTO.go
  wire_gen.go
Labels: PR:Ready-to-Review

#3980 fix: ci pod request correction
  pkg/pipeline/WorkflowUtils.go
Labels: PR:Ready-to-Review

#3984 fix: pipelineOverride id being sent instead of pipelineId
  pkg/pipeline/WorkflowDagExecutor.go
Labels: PR:Ready-to-Review

#3971 feat:Poll Images from ECR Container Repository Plugin
  Wire.go
  api/restHandler/app/BuildPipelineRestHandler.go
  api/router/pubsub/CiEventHandler.go
  api/router/router.go
  assets/plugin-poll-container-registry.png
  client/cron/CiTriggerCron.go
  go.mod
  go.sum
  internal/sql/repository/CiArtifactRepository.go
  internal/sql/repository/pipelineConfig/CiPipelineRepository.go
  pkg/appClone/AppCloneService.go
  pkg/bean/app.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowUtils.go
  pkg/pipeline/bean/CiBuildConfig.go
  pkg/pipeline/bean/workFlowRequestBean.go
  pkg/pipeline/repository/PipelineStageRepository.go
  pkg/plugin/repository/GlobalPluginRepository.go
  scripts/sql/172_ci_pipeline_job.down.sql
  scripts/sql/172_ci_pipeline_job.up.sql
  scripts/sql/173_polling_plugin.down.sql
  scripts/sql/173_polling_plugin.up.sql
  util/helper.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/LICENSE.txt
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/types/enums.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/types/errors.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/types/types.go
  vendor/github.com/aws/smithy-go/.gitignore
  vendor/github.com/aws/smithy-go/.travis.yml
  vendor/github.com/aws/smithy-go/CHANGELOG.md
  vendor/github.com/aws/smithy-go/CODE_OF_CONDUCT.md
  vendor/github.com/aws/smithy-go/CONTRIBUTING.md
  vendor/github.com/aws/smithy-go/LICENSE
  vendor/github.com/aws/smithy-go/Makefile
  vendor/github.com/aws/smithy-go/NOTICE
  vendor/github.com/aws/smithy-go/README.md
  vendor/github.com/aws/smithy-go/doc.go
  vendor/github.com/aws/smithy-go/document.go
  vendor/github.com/aws/smithy-go/document/doc.go
  vendor/github.com/aws/smithy-go/document/document.go
  vendor/github.com/aws/smithy-go/document/errors.go
  vendor/github.com/aws/smithy-go/errors.go
  vendor/github.com/aws/smithy-go/go_module_metadata.go
  vendor/github.com/aws/smithy-go/local-mod-replace.sh
  vendor/github.com/aws/smithy-go/modman.toml
  vendor/github.com/aws/smithy-go/properties.go
  vendor/github.com/aws/smithy-go/validation.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#3995 fix: Iam role handling script for plugin pull image from CR
  scripts/sql/174_container_image_update.down.sql
  scripts/sql/174_container_image_update.up.sql
Labels: PR:Ready-to-Review

#3977 chore: Scoped variable refactoring
  Wire.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/scopedVariable/ScopedVariableRestHandler.go
  pkg/app/AppService.go
  pkg/chart/ChartService.go
  pkg/devtronResource/DevtronResourceService.go
  pkg/devtronResource/bean/bean.go
  pkg/devtronResource/mocks/DevtronResourceService.go
  pkg/devtronResource/repository/DevtronResourceSearchableKeyRepository.go
  pkg/devtronResource/repository/mocks/DevtronResourceSearchableKeyRepository.go
  pkg/pipeline/CiService.go
  pkg/pipeline/DeploymentConfigService.go
  pkg/pipeline/PipelineStageService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/resourceQualifiers/QualifierMappingService.go
  pkg/resourceQualifiers/ResourceQualifiersMappingDto.go
  pkg/resourceQualifiers/ResourceQualifiersMappingRepository.go
  pkg/resourceQualifiers/bean.go
  pkg/resourceQualifiers/mocks/QualifierMappingService.go
  pkg/variables/ScopedVariableService.go
  pkg/variables/helper/mappers.go
  pkg/variables/helper/priority-manager.go
  pkg/variables/models/service-models.go
  pkg/variables/models/variable-payload.go
  pkg/variables/repository/ScopedVariableDto.go
  pkg/variables/repository/ScopedVariableRepository.go
  scripts/sql/175_resource_filter.down.sql
  scripts/sql/175_resource_filter.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#3974 feat: resource groups CRUD and environment filtering
  Wire.go
  api/restHandler/AppGroupRestHandler.go
  api/restHandler/AppWorkflowRestHandler.go
  api/restHandler/ResourceGroupRestHandler.go
  api/restHandler/app/BuildPipelineRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/router/AppGroupingRouter.go
  api/router/ResourceGroupingRouter.go
  api/router/router.go
  internal/sql/repository/appGroup/AppGroupMappingRepository.go
  internal/sql/repository/appGroup/AppGroupRepository.go
  internal/sql/repository/pipelineConfig/CiPipelineRepository.go
  internal/sql/repository/resourceGroup/ResourceGroupMappingRepository.go
  internal/sql/repository/resourceGroup/ResourceGroupRepository.go
  pkg/appGroup/AppGroupService.go
  pkg/appWorkflow/AppWorkflowService.go
  pkg/cluster/EnvironmentService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/mock_pipeline/PipelineBuilder.go
  pkg/resourceGroup/ResourceGroupService.go
  scripts/sql/176_resource_group.down.sql
  scripts/sql/176_resource_group.up.sql
  util/TypeUtils.go
  util/rbac/EnforcerUtil.go
  wire_gen.go
Labels: PR:Ready-to-Review
