Repository devtron-labs/devtron, pull requests merged in 2023-06, with the labels that each got.

#3443 fix: argocd-cm empty data label nil pointer fix
  pkg/chartRepo/ChartRepositoryService.go
Labels: pager-duty

#3339 fix: App delete from ACD with non cascade
  api/appStore/AppStoreRouter.go
  api/appStore/InstalledAppRestHandler.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/cluster/EnvironmentRestHandler.go
  api/cluster/EnvironmentRouter.go
  api/restHandler/BulkUpdateRestHandler.go
  api/restHandler/CoreAppRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/router/PipelineConfigRouter.go
  api/router/pubsub/ApplicationStatusHandler.go
  cmd/external-app/wire_gen.go
  pkg/appStore/bean/bean.go
  pkg/appStore/deployment/repository/InstalledAppRepository.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/bean/app.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/bulkAction/bean.go
  pkg/cluster/ClusterService.go
  pkg/cluster/EnvironmentService.go
  pkg/pipeline/GitopsOrHelmOption_test.go
  pkg/pipeline/PipelineBuilder.go
  util/k8s/k8sApplicationService.go
  wire_gen.go
Labels: enhancement

#3506 fix: acd app delete non cascade
  api/appStore/AppStoreRouter.go
  api/appStore/InstalledAppRestHandler.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/cluster/EnvironmentRestHandler.go
  api/cluster/EnvironmentRouter.go
  api/restHandler/BulkUpdateRestHandler.go
  api/restHandler/CoreAppRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/router/PipelineConfigRouter.go
  api/router/pubsub/ApplicationStatusHandler.go
  cmd/external-app/wire_gen.go
  pkg/appStore/bean/bean.go
  pkg/appStore/deployment/repository/InstalledAppRepository.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/bean/app.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/bulkAction/bean.go
  pkg/cluster/ClusterService.go
  pkg/cluster/EnvironmentService.go
  pkg/pipeline/GitopsOrHelmOption_test.go
  pkg/pipeline/PipelineBuilder.go
  util/k8s/k8sApplicationService.go
  wire_gen.go
Labels: duplicate

#3200 fix: Remove argocd server calls for Application resources (Manifest, Event, Logs, Terminal)
  api/helm-app/HelmAppService.go
  client/k8s/application/Application.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/pipeline/PipelineBuilder.go
  util/ValidatorHelper.go
  util/k8s/k8sApplicationRestHandler.go
  util/k8s/k8sApplicationService.go
Labels: bug

#3552 fix: ACD helm app release not found when deleting resource
  util/k8s/k8sApplicationRestHandler.go
Labels: enhancement

#3555 feat: Enforce a deployment tool (Helm / ArgoCD) for a particular environment/cluster
  Makefile
  api/cluster/EnvironmentRestHandler.go
  api/restHandler/app/AutoCompleteRestHandler.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/mocks/AttributesRepository.go
  pkg/cluster/EnvironmentService.go
  pkg/cluster/EnvironmentService_test.go
  pkg/pipeline/GitopsOrHelmOption_test.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/PipelineBuilder_test.go
  wire_gen.go
Labels: enhancement
