Repository devtron-labs/devtron, pull requests merged in 2023-11, with the labels that each got.

#4180 chore: struct type refactored
  Wire.go
  api/restHandler/DockerRegRestHandler.go
  api/restHandler/MigrateDbRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/router/pubsub/WorkflowStatusUpdateHandler.go
  pkg/delete/DeleteService.go
  pkg/delete/DeleteServiceFullMode.go
  pkg/pipeline/ArgoWorkflowExecutor_test.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/DbConfigService.go
  pkg/pipeline/DbMigrationService.go
  pkg/pipeline/DockerRegistryConfig.go
  pkg/pipeline/DockerRegistryConfig_test.go
  pkg/pipeline/GlobalCmcsService_test.go
  pkg/pipeline/SystemWorkflowExecutor_test.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/WorkflowServiceIT_test.go
  pkg/pipeline/executors/ArgoWorkflowExecutor.go
  pkg/pipeline/executors/SystemWorkflowExecutor.go
  pkg/pipeline/executors/WorkflowUtils.go
  pkg/pipeline/types/DbConfig.go
  pkg/pipeline/types/DockerRegistry.go
  pkg/pipeline/types/Workflow.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4185 release: Release v0.6.24 fix for not able to edit cluster
  charts/devtron/Chart.yaml
  charts/devtron/devtron-bom.yaml
  charts/devtron/values.yaml
  manifests/yamls/devtron.yaml
Labels: PR:Ready-to-Review

#4183 fix: Stable dt19 v3 + v4 bugathon bug fixes
  api/helm-app/HelmAppService.go
  api/helm-app/models/customErrors.go
  api/user/UserRestHandler.go
  go.mod
  go.sum
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
  internal/sql/repository/pipelineConfig/CiPipelineRepository.go
  pkg/cluster/EnvironmentService.go
  pkg/cluster/repository/EnvironmentRepository.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/user/RoleGroupService.go
  pkg/user/bean/bean.go
  pkg/user/util/util.go
  util/k8s/K8sUtil_test.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4195 fix: ImageScanDeployInfo not initialized while fetching from db
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
Labels: PR:Ready-to-Review

#4169 docs: Added Videos + Fixed Typos and Navigation
  docs/SUMMARY.md
  docs/setup/install/demo-tutorials.md
  docs/setup/install/install-devtron-with-cicd.md
  docs/user-guide/creating-application/config-approval.md
  docs/user-guide/use-cases/oci-pull.md
Labels: PR:Ready-to-Review

#4174 feat: scoped variable CMCS support and manager layer refactorings
  Wire.go
  api/bean/ConfigMapAndSecret.go
  internal/sql/repository/chartConfig/EnvConfigOverrideRepository.go
  pkg/app/AppService.go
  pkg/bean/configSecretData.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/chart/ChartService.go
  pkg/generateManifest/DeployementTemplateService.go
  pkg/pipeline/CiService.go
  pkg/pipeline/ConfigMapService.go
  pkg/pipeline/DeploymentConfigService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/PipelineStageService.go
  pkg/pipeline/PropertiesConfig.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/bean/ConfigMapBean.go
  pkg/pipeline/history/ConfigMapHistoryService.go
  pkg/pipeline/history/DeployedConfigurationHistoryService.go
  pkg/pipeline/history/DeploymentTemplateHistoryService.go
  pkg/pipeline/history/PrePostCdScriptHistoryService.go
  pkg/pipeline/history/bean.go
  pkg/pipeline/history/mocks/ConfigMapHistoryService.go
  pkg/pipeline/types/Workflow.go
  pkg/variables/ScopedVariableCMCSManager.go
  pkg/variables/ScopedVariableManager.go
  pkg/variables/models/service-models.go
  pkg/variables/parsers/bean.go
  pkg/variables/repository/VariableEntityDTO.go
  pkg/variables/repository/VariableSnapshotHistoryDTO.go
  pkg/variables/utils/conversion-utils.go
  util/TypeUtils.go
  util/encoding-utils.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4021 feat: Plugin for image scanning in Pre/Post step
  assets/ic-plugin-vulnerability-scan.png
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/bean/pipelineStage.go
  pkg/pipeline/bean/workFlowRequestBean.go
  pkg/pipeline/repository/PipelineStageRepository.go
  pkg/pipeline/types/Workflow.go
  scripts/sql/184_image_scan_plugin.down.sql
  scripts/sql/184_image_scan_plugin.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#4154 feat: Description for cluster and apps
  api/appStore/AppStoreRouter.go
  api/appStore/InstalledAppRestHandler.go
  api/bean/AppView.go
  api/cluster/ClusterRestHandler.go
  api/cluster/ClusterRouter.go
  api/restHandler/AppRestHandler.go
  api/restHandler/CoreAppRestHandler.go
  api/router/AppRouter.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/AppListingRepository.go
  internal/sql/repository/app/AppRepository.go
  internal/util/ArgoUtil/ArgoClient.go
  internal/util/GitService.go
  pkg/app/AppCrudOperationService.go
  pkg/appClone/AppCloneService.go
  pkg/bean/app.go
  pkg/chartRepo/ChartRepositoryService.go
  pkg/cluster/ClusterDescriptionService.go
  pkg/cluster/ClusterService.go
  pkg/cluster/repository/ClusterDescriptionRepository.go
  pkg/cluster/repository/ClusterRepository.go
  pkg/genericNotes/tests/GenericNoteService_test.go
  pkg/gitops/GitOpsConfigService.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/GitRegistryConfig.go
  pkg/plugin/GlobalPluginService.go
  pkg/resourceGroup/ResourceGroupService.go
  scripts/sql/185_alter_cluster_add_description.down.sql
  scripts/sql/185_alter_cluster_add_description.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#4161 feat: Run jobs using system executor
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
  pkg/cluster/ClusterService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/executors/ArgoWorkflowExecutor.go
  pkg/pipeline/executors/SystemWorkflowExecutor.go
  pkg/pipeline/types/Workflow.go
  scripts/sql/186_executor_type_in_ci.down.sql
  scripts/sql/186_executor_type_in_ci.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#3982 docs: Scoped Variables Draft + Other Fixes (Ephemeral Doc Alignment)
  docs/SUMMARY.md
  docs/user-guide/app-details/ephemeral-containers.md
  docs/user-guide/global-configurations/scoped-variables.md
Labels: PR:Ready-to-Review

#4175 chore: resource sql migration script
  Wire.go
  pkg/devtronResource/DevtronResourceSearchableKeyService.go
  pkg/resourceGroup/ResourceGroupService.go
  pkg/resourceQualifiers/QualifierMappingService.go
  pkg/variables/ScopedVariableService.go
  scripts/sql/187_create_resource.down.sql
  scripts/sql/187_create_resource.up.sql
Labels: PR:Ready-to-Review

#4214 doc: GC Index Additions + Fixes
  docs/SUMMARY.md
  docs/user-guide/global-configurations/README.md
Labels: PR:Ready-to-Review

#4215 fix: setting cipipelineId to parent ci-pipelines id for linked ci's
  pkg/dockerRegistry/DockerRegistryIpsConfigService.go
Labels: PR:Ready-to-Review

#4220 fix: update docker config overridden flag in linked ci's
  pkg/pipeline/CiCdPipelineOrchestrator.go
Labels: PR:Ready-to-Review

#4226 Delete cipipeline
  internal/sql/repository/appWorkflow/AppWorkflowRepository.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#4219 fix:post-cd plugin not getting added again, after removing and adding again
  pkg/pipeline/PipelineStageService.go
Labels: PR:Ready-to-Review

#4137 chore: artifact api refactoring
  api/bean/ValuesOverrideRequest.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  go.mod
  go.sum
  internal/sql/repository/CiArtifactRepository.go
  internal/sql/repository/CiArtifactsListingQueryBuilder.go
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
  pkg/bean/app.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/CiService.go
  scripts/sql/188_resource_filter_audit_update.down.sql
  scripts/sql/188_resource_filter_audit_update.up.sql
  vendor/github.com/samber/lo/.gitignore
  vendor/github.com/samber/lo/.travis.yml
  vendor/github.com/samber/lo/CHANGELOG.md
  vendor/github.com/samber/lo/Dockerfile
  vendor/github.com/samber/lo/LICENSE
  vendor/github.com/samber/lo/Makefile
  vendor/github.com/samber/lo/README.md
  vendor/github.com/samber/lo/channel.go
  vendor/github.com/samber/lo/concurrency.go
  vendor/github.com/samber/lo/condition.go
  vendor/github.com/samber/lo/constraints.go
  vendor/github.com/samber/lo/errors.go
  vendor/github.com/samber/lo/find.go
  vendor/github.com/samber/lo/func.go
  vendor/github.com/samber/lo/intersect.go
  vendor/github.com/samber/lo/map.go
  vendor/github.com/samber/lo/math.go
  vendor/github.com/samber/lo/retry.go
  vendor/github.com/samber/lo/slice.go
  vendor/github.com/samber/lo/string.go
  vendor/github.com/samber/lo/tuples.go
  vendor/github.com/samber/lo/type_manipulation.go
  vendor/github.com/samber/lo/types.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4247 fix: kubernetes events fix for resources
  go.mod
  go.sum
  internal/sql/repository/CiArtifactsListingQueryBuilder.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#3937 feat: add plugin via api
  api/restHandler/GlobalPluginRestHandler.go
  api/router/GlobalPluginRouter.go
  api/router/router.go
  pkg/pipeline/repository/PipelineStageRepository.go
  pkg/plugin/GlobalPluginService.go
  pkg/plugin/bean.go
  pkg/plugin/repository/GlobalPluginRepository.go
  pkg/plugin/utils.go
  pkg/sql/UtilStructs.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4253 docs: Added Filter Doc in Index
  docs/SUMMARY.md
Labels: PR:Ready-to-Review

#4240 fix: deleted service showing port as missing fix
  pkg/k8s/K8sCommonService.go
Labels: PR:Ready-to-Review

#4207 chore: Update pr-issue-validator.yaml
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#4209 feat: copy container images
  Wire.go
  api/bean/CustomTag.go
  api/bean/ValuesOverrideRequest.go
  api/restHandler/PipelineTriggerRestHandler.go
  api/restHandler/app/BuildPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/router/ApplicationRouter.go
  api/router/pubsub/CiEventHandler.go
  api/router/pubsub/WorkflowStatusUpdateHandler.go
  assets/ic-plugin-copy-container-image.png
  internal/sql/repository/CiArtifactRepository.go
  internal/sql/repository/CiArtifactsListingQueryBuilder.go
  internal/sql/repository/CustomTagRepository.go
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
  pkg/bean/app.go
  pkg/dockerRegistry/DockerRegistryIpsConfigService.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/pipeline/CustomTagService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/StageServiceUtil.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/bean/CustomTagService.go
  pkg/pipeline/pipelineStageVariableParser.go
  pkg/pipeline/types/Workflow.go
  pkg/plugin/GlobalPluginService.go
  pkg/plugin/bean.go
  scripts/sql/190_copy_container_images.down.sql
  scripts/sql/190_copy_container_images.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#4265 chore: updating dependency tracker maven plugin name
  scripts/sql/189_update_mvn_dependency_tracker_plugin.up.sql
Labels: PR:Ready-to-Review

#4045 feat: Helm async deploy Devtron Apps
  Wire.go
  api/bean/ValuesOverrideRequest.go
  api/helm-app/HelmAppService.go
  api/helm-app/applist.pb.go
  api/helm-app/applist.proto
  api/helm-app/applist_grpc.pb.go
  go.mod
  go.sum
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
  internal/util/CollectionUtil.go
  internal/util/ErrorUtil.go
  pkg/app/AppListingService.go
  pkg/app/AppService.go
  pkg/app/integrationTest/AppService_test.go
  pkg/bean/app.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/PipelineConfigServiceListener.go
  pkg/pipeline/WorkflowDagExecutor.go
  scripts/sql/191_devtron_app_async_install.down.sql
  scripts/sql/191_devtron_app_async_install.up.sql
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
  vendor/github.com/samber/lo/.gitignore
  vendor/github.com/samber/lo/.travis.yml
  vendor/github.com/samber/lo/CHANGELOG.md
  vendor/github.com/samber/lo/Dockerfile
  vendor/github.com/samber/lo/LICENSE
  vendor/github.com/samber/lo/Makefile
  vendor/github.com/samber/lo/README.md
  vendor/github.com/samber/lo/channel.go
  vendor/github.com/samber/lo/concurrency.go
  vendor/github.com/samber/lo/condition.go
  vendor/github.com/samber/lo/constraints.go
  vendor/github.com/samber/lo/errors.go
  vendor/github.com/samber/lo/find.go
  vendor/github.com/samber/lo/func.go
  vendor/github.com/samber/lo/intersect.go
  vendor/github.com/samber/lo/map.go
  vendor/github.com/samber/lo/math.go
  vendor/github.com/samber/lo/retry.go
  vendor/github.com/samber/lo/slice.go
  vendor/github.com/samber/lo/string.go
  vendor/github.com/samber/lo/tuples.go
  vendor/github.com/samber/lo/type_manipulation.go
  vendor/github.com/samber/lo/types.go
  vendor/modules.txt
  wire_gen.go
Labels: enhancement, PR:Ready-to-Review

#4267 fix: DevtronApp Deployment Status Fixed
  go.mod
  go.sum
  pkg/pipeline/CdHandler.go
  pkg/pipeline/WorkflowDagExecutor.go
  vendor/modules.txt
Labels: enhancement, PR:Ready-to-Review

#4269 fix: No rows for rest config in case of Default namespace
  pkg/pipeline/CiHandler.go
Labels: PR:Ready-to-Review

#4235 docs: App Configuration Corrections + Structuring
  docs/SUMMARY.md
  docs/user-guide/creating-application/README.md
  docs/user-guide/creating-application/external-links.md
Labels: PR:Ready-to-Review

#4273 fix: old custom tag migration
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CustomTagService.go
  scripts/sql/192_custom_tag_migration.down.sql
  scripts/sql/192_custom_tag_migration.up.sql
Labels: PR:Ready-to-Review

#4282 fix: updated copy container image plugin for multi arc build support
  scripts/sql/193_copy_container_images_updated.down.sql
  scripts/sql/193_copy_container_images_updated.up.sql
Labels: enhancement, PR:Ready-to-Review

#4292 fix: Get Artifacts list API is throwing pg no rows error
  internal/sql/repository/CiArtifactsListingQueryBuilder.go
  pkg/dockerRegistry/DockerRegistryIpsConfigService.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/CiService.go
  pkg/pipeline/WebhookService.go
Labels: enhancement, PR:Ready-to-Review

#4296 fix: Job trigger throws error
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/CiService.go
Labels: PR:Ready-to-Review

#4301 docs: img size fix
  docs/user-guide/global-configurations/scoped-variables.md
Labels: PR:Ready-to-Review

#4229 feat: Bulk Hibernate
  api/bean/AppView.go
  api/restHandler/BulkUpdateRestHandler.go
  internal/sql/repository/AppListingRepository.go
  internal/sql/repository/appStatus/AppStatusRepository.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/app/AppListingService.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/bulkAction/bean.go
  pkg/resourceGroup/ResourceGroupService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4300 fix: limit ci build message length to 250
  pkg/pipeline/CiHandler.go
Labels: PR:Ready-to-Review

#4315 fix: app-group page breaking for inactive users
  internal/sql/repository/AppListingRepository.go
  pkg/app/AppListingService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4251 chore: change CI backend infra
  Wire.go
  api/bean/AppView.go
  api/restHandler/app/BuildPipelineRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  internal/sql/repository/AppListingRepository.go
  internal/sql/repository/CiArtifactRepository.go
  internal/sql/repository/appWorkflow/AppWorkflowRepository.go
  internal/sql/repository/pipelineConfig/CiPipelineRepository.go
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/appClone/AppCloneService.go
  pkg/bean/app.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/BuildPipelineSwitchService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/WorkflowServiceIT_test.go
  pkg/pipeline/history/DeployedConfigurationHistoryService.go
  pkg/variables/ScopedVariableService.go
  scripts/sql/194_parent_ci_remove_constraint.down.sql
  scripts/sql/194_parent_ci_remove_constraint.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#4323 fix: Message not updating for Ci
  pkg/pipeline/CiHandler.go
Labels: PR:Ready-to-Review
