Repository devtron-labs/devtron, pull requests merged in 2023-12, with the labels that each got.

#4330 fix: not able to add env in global configuration
  pkg/cluster/EnvironmentService.go
  pkg/cluster/repository/EnvironmentRepository.go
Labels: enhancement, PR:Ready-to-Review

#4331 fix: unhibernation is getting initiated for already unhibernated apps
  pkg/bulkAction/BulkUpdateService.go
Labels: PR:Issue-verification-failed

#4266 chore: updated schema for resources
  scripts/sql/196_alter_resource_schema.down.sql
  scripts/sql/196_alter_resource_schema.up.sql
Labels: PR:Ready-to-Review

#4350 fix: cm-env override
  api/restHandler/ConfigMapRestHandler.go
Labels: PR:Ready-to-Review

#4237 fix:rbac is not in sync with Actual application status
  pkg/user/UserAuthService.go
  pkg/user/repository/UserAuthRepository.go
Labels: PR:Ready-to-Review

#4275 doc: Added Application Groups Doc
  docs/SUMMARY.md
  docs/user-guide/application-groups.md
Labels: PR:Ready-to-Review

#4353 fix: Inconsistent behaviour on deploying application from application group v/s devtron cli tool after changing deploymentType
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/appWorkflow/AppWorkflowService.go
Labels: PR:Ready-to-Review

#4359 fix: added missing clusterConfig in releaseIdentifier request
  api/helm-app/HelmAppService.go
  pkg/appStore/deployment/service/InstalledAppService.go
Labels: PR:Ready-to-Review

#4347 fix:cve search
  internal/sql/repository/security/CveStoreRepository.go
  pkg/security/ImageScanService.go
Labels: PR:Ready-to-Review

#4284 fix:Not able to change Authentication Type for Prometheus.
  pkg/bean/app.go
  pkg/cluster/ClusterService.go
Labels: PR:Ready-to-Review

#4372 release: Disabled artifact api listing v2
  charts/devtron/Chart.yaml
  charts/devtron/templates/devtron.yaml
Labels: PR:Ready-to-Review

#4375 fix: optimised the artifacts listing query and added query versioned support
  api/bean/ValuesOverrideRequest.go
  internal/sql/repository/CiArtifactRepository.go
  internal/sql/repository/CiArtifactsListingQueryBuilder.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/types/CiCdConfig.go
Labels: PR:Ready-to-Review

#4271 chore: made devtron namespace configurable in authenticator
  go.mod
  go.sum
  vendor/github.com/devtron-labs/authenticator/client/k8sClient.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4381 chore: Update pager-duty Issue template
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/pager-duty.yaml
Labels: PR:Ready-to-Review

#4380 docs: Gitbook assets moved to AWS S3
  docs/.gitbook/assets/preview.gif
  docs/user-guide/app-details/README.md
  docs/user-guide/app-details/terminal.md
  docs/user-guide/app-labels.md
  docs/user-guide/bulk-update.md
  docs/user-guide/creating-application/config-maps.md
  docs/user-guide/creating-application/deployment-template/deployment.md
  docs/user-guide/creating-application/deployment-template/statefulset.md
  docs/user-guide/creating-application/docker-build-configuration.md
  docs/user-guide/creating-application/environment-overrides.md
  docs/user-guide/creating-application/workflow/README.md
  docs/user-guide/creating-application/workflow/automated-test.md
  docs/user-guide/creating-application/workflow/ci-pipeline-legacy.md
  docs/user-guide/creating-application/workflow/ci-pipeline.md
  docs/user-guide/global-configurations/manage-notification.md
  docs/user-guide/security-features.md
  docs/user-guide/use-cases/connect-django-with-mysql-database.md
  docs/user-guide/use-cases/connect-expressjs-with-mongodb-database.md
  docs/user-guide/use-cases/connect-springboot-with-mysql-database.md
  docs/user-guide/use-cases/devtron-generic-helm-chart-to-run-cron-job-or-one-time-job.md
  docs/user-guide/user-guide.md
Labels: PR:Ready-to-Review

#4367 doc: Indentation fix in Scoped Variable Doc
  docs/user-guide/global-configurations/scoped-variables.md
Labels: PR:Ready-to-Review

#4394 doc: Redirection added for OCI doc
  .gitbook.yaml
Labels: PR:Ready-to-Review

#4293 chore: enhancements in User Service and User common service
  api/apiToken/ApiTokenRestHandler.go
  api/appStore/InstalledAppRestHandler.go
  api/cluster/ClusterRestHandler.go
  api/cluster/EnvironmentRestHandler.go
  api/helm-app/HelmAppRestHandler.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/restHandler/BulkUpdateRestHandler.go
  api/restHandler/CoreAppRestHandler.go
  api/restHandler/DeploymentGroupRestHandler.go
  api/restHandler/DockerRegRestHandler.go
  api/restHandler/ExternalCiRestHandler.go
  api/restHandler/GitHostRestHandler.go
  api/restHandler/GitProviderRestHandler.go
  api/restHandler/MigrateDbRestHandler.go
  api/restHandler/NotificationRestHandler.go
  api/restHandler/app/BuildPipelineRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/team/TeamRestHandler.go
  api/user/UserRestHandler.go
  internal/sql/repository/app/AppRepository.go
  internal/sql/repository/security/ScanToolMetaDataRepository.go
  pkg/appWorkflow/AppWorkflowService.go
  pkg/user/RoleGroupService.go
  pkg/user/UserAuthService.go
  pkg/user/UserCommonService.go
  pkg/user/UserService.go
  pkg/user/casbin/Adapter.go
  pkg/user/casbin/rbac.go
  pkg/user/repository/RoleGroupRepository.go
  pkg/user/repository/UserAuthRepository.go
  pkg/user/repository/bean.go
Labels: PR:Ready-to-Review

#4402 docs: Typos fixed in multiple docs (Phase 1)
  docs/FAQs/devtron-troubleshoot.md
  docs/hyperion/user-guide/global-configurations/cluster-and-environments.md
  docs/hyperion/user-guide/global-configurations/user-access.md
  docs/reference/glossary.md
  docs/setup/getting-started/why-devtron.md
  docs/setup/install/install-devtron-helm-3.md
  docs/user-guide/app-labels.md
  docs/user-guide/cloning-application.md
  docs/user-guide/clusters.md
  docs/user-guide/creating-application/app-metrics.md
  docs/user-guide/creating-application/container-registry-override.md
  docs/user-guide/creating-application/deployment-template/deployment.md
  docs/user-guide/creating-application/deployment-template/rollout-deployment.md
  docs/user-guide/creating-application/deployment-template/statefulset.md
  docs/user-guide/creating-application/docker-build-configuration.md
  docs/user-guide/creating-application/overview.md
  docs/user-guide/creating-application/secrets.md
  docs/user-guide/creating-application/workflow/cd-pipeline.md
  docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
  docs/user-guide/creating-application/workflow/ci-pipeline-legacy.md
  docs/user-guide/creating-application/workflow/ci-pipeline.md
  docs/user-guide/global-configurations/external-links.md
  docs/user-guide/integrations/clair.md
  docs/user-guide/jobs/create-job.md
  docs/user-guide/jobs/overview-job.md
  docs/user-guide/jobs/triggering-job.md
  docs/user-guide/jobs/workflow-editor-job.md
  docs/user-guide/resource-browser.md
Labels: PR:Ready-to-Review

#4396 feat: Integrate Cloudanix Image Scanner Plugin for Advanced Image Scanning
  assets/cloudanix-logo.png
  scripts/sql/202_cloudanix_imagescan.down.sql
  scripts/sql/202_cloudanix_imagescan.up.sql
Labels: PR:Ready-to-Review

#4411 feat: CS create bucket plugin
  assets/gcs-bucket.svg
  scripts/sql/203_create_gcs_bucket.down.sql
  scripts/sql/203_create_gcs_bucket.up.sql
Labels: PR:Ready-to-Review

#4404 feat: flag driven tag based build propogate same tag for CI Build
  pkg/pipeline/CiService.go
  pkg/pipeline/types/CiCdConfig.go
Labels: PR:Ready-to-Review

#4407 fix: error handling and url fix
  client/grafana/GrafanaClient.go
Labels: PR:Ready-to-Review

#4097 doc: fixed broken link and improved documentation in usecases
  docs/user-guide/use-cases/README.md
Labels: documentation, PR:Ready-to-Review

#4374 chore: migration for global resource schema
  scripts/sql/206_alter_resource.down.sql
  scripts/sql/206_alter_resource.up.sql
Labels: PR:Ready-to-Review

#4357 feat: skip bulk build source change
  pkg/bean/app.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/PipelineBuilder.go
Labels: PR:Ready-to-Review

#4422 chore: share same nats url used by orchestrator
  pkg/pipeline/types/CiCdConfig.go
  pkg/pipeline/types/Workflow.go
Labels: PR:Ready-to-Review

#4429 doc: Update Helm Installation Command
  config.md
  docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
  docs/setup/install/install-devtron-helm-3.md
  docs/setup/install/install-devtron-with-cicd-with-gitops.md
  docs/setup/install/install-devtron-with-cicd.md
  docs/setup/install/install-devtron.md
  docs/setup/install/installation-configuration.md
Labels: PR:Ready-to-Review

#4441 fix: linked ci failing for null pipeline_type
  scripts/sql/207_ci_external.down.sql
  scripts/sql/207_ci_external.up.sql
Labels: PR:Ready-to-Review

#4398 feat: add or delete CD pipelines from workflow
  internal/sql/repository/appWorkflow/AppWorkflowRepository.go
  pkg/appClone/AppCloneService.go
  pkg/appWorkflow/AppWorkflowService.go
  pkg/bean/app.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/BuildPipelineSwitchService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/variables/utils/conversion-utils.go
Labels: PR:Ready-to-Review

#4449 fix: Manual sync job fix
  pkg/chartRepo/ChartRepositoryService.go
Labels: PR:Ready-to-Review

#4454 fix: empty pod name
  pkg/pipeline/CiHandler.go
Labels: PR:Ready-to-Review

#4467 chore: add back argo-assets
  vendor/github.com/argoproj/argo-cd/assets/badge.svg
  vendor/github.com/argoproj/argo-cd/assets/builtin-policy.csv
  vendor/github.com/argoproj/argo-cd/assets/model.conf
  vendor/github.com/argoproj/argo-cd/assets/swagger.json
Labels: PR:Ready-to-Review

#4461 fix: app clone breaking if ci pipeline have same name
  api/restHandler/CoreAppRestHandler.go
  api/restHandler/app/BuildPipelineRestHandler.go
  pkg/appClone/AppCloneService.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/bean/CiBuildConfig.go
Labels: PR:Ready-to-Review

#4471 fix: handle argo delete event for charts and added socket config
  api/router/pubsub/ApplicationStatusHandler.go
  pkg/terminal/terminalSesion.go
Labels: PR:Ready-to-Review

#4392 feat: manual sync for argocd apps
  Dockerfile
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/appStore/deployment/wire_appStoreDeployment.go
  client/argocdServer/ArgoClientWrapperService.go
  client/argocdServer/k8sClient.go
  client/cron/CdApplicationStatusUpdateHandler.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/pipelineConfig/PipelineStatusTimelineRepository.go
  pkg/app/AppService.go
  pkg/app/ManifestPushService.go
  pkg/app/status/PipelineStatusTimelineService.go
  pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
  pkg/appStore/deployment/repository/InstalledAppVersionHistory.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/WorkflowDagExecutor.go
  scripts/argo-assets/APPLICATION_TEMPLATE.tmpl
  wire_gen.go
Labels: PR:Ready-to-Review

#4475 chore: Update Issues template and codeowners
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug.yaml
  .github/ISSUE_TEMPLATE/documentation.yaml
  .github/ISSUE_TEMPLATE/feature.yaml
  .github/ISSUE_TEMPLATE/pager-duty.yaml
Labels: PR:Ready-to-Review

#4477 doc: Added Minikube Tutorial + Restructured Doc
  docs/SUMMARY.md
  docs/setup/install/Install-devtron-on-Minikube-Microk8s-K3s-Kind.md
Labels: PR:Ready-to-Review
