Repository devtron-labs/devtron, pull requests merged in 2023-03, with the labels that each got.

#2958 feat - Use cluster-name instead of server url in Argo cd application objects
  client/argocdServer/k8sClient.go
  pkg/app/AppService.go
  pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
  scripts/argo-assets/APPLICATION_TEMPLATE.JSON
Labels: good first issue

#2970 fix: Helm repository deleted from argocd-cm when deleted from UI (Github Issue #1399)
  pkg/chartRepo/ChartRepositoryService.go
  pkg/chartRepo/ChartRepositoryService_test.go
  pkg/delete/DeleteService.go
  pkg/delete/DeleteServiceExtended.go
Labels: bug

#2948 fix: rbac optimisation for creation of policies for devtron app, helm app and cluster
  api/user/UserAuthHandler.go
  api/user/UserRestHandler.go
  pkg/appStore/deployment/service/ChartGroupService.go
  pkg/cluster/EnvironmentService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/team/TeamService.go
  pkg/user/RoleGroupService.go
  pkg/user/UserAuthService.go
  pkg/user/UserCommonService.go
  pkg/user/UserService.go
  pkg/user/bean/bean.go
  pkg/user/repository/DefaultAuthPolicyRepository.go
  pkg/user/repository/DefaultAuthRoleRepository.go
  pkg/user/repository/RoleGroupRepository.go
  pkg/user/repository/UserAuthRepository.go
  pkg/user/repository/UserRepository.go
  scripts/sql/124_helm_policy_access-type.down.sql
  scripts/sql/124_helm_policy_access-type.up.sql
Labels: enhancement
