Repository devtron-labs/devtron, pull requests merged in 2024-06, with the labels that each got.

#5152 fix: fixing force push for gitops
  pkg/deployment/gitOps/git/GitOpsHelper.go
  pkg/deployment/gitOps/git/commandManager/GitCliManager.go
  pkg/deployment/gitOps/git/commandManager/GitCommandBaseManager.go
Labels: PR:Ready-to-Review

#5168 fix: update CVE's severity and store multiple same CVE's in multiple packages
  internal/sql/repository/security/CveStoreRepository.go
  internal/sql/repository/security/ImageScanResultRepository.go
  pkg/security/ImageScanService.go
  pkg/security/policyService.go
  scripts/sql/251_alter_image_scan_result_repository.down.sql
  scripts/sql/251_alter_image_scan_result_repository.up.sql
Labels: PR:Ready-to-Review

#4998 docs: update readme to include multi arch flag
  README.md
Labels: PR:Ready-to-Review

#5203 doc: Added enhancements to security doc
  .gitbook.yaml
  docs/reference/glossary.md
  docs/user-guide/application-groups.md
  docs/user-guide/security-features.md
Labels: documentation, PR:Ready-to-Review

#5200 feat: cd pipeline deployment history refactoring
  Wire.go
  api/devtronResource/DevtronResourceHistoryRestHandler.go
  api/devtronResource/DevtronResourceHistoryRouter.go
  api/devtronResource/DevtronResourceRestHandler.go
  api/devtronResource/DevtronResourceRouter.go
  api/devtronResource/bean/bean.go
  api/devtronResource/wire_devtronResource.go
  api/router/router.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/devtronResource/APIReqDecoderService.go
  pkg/devtronResource/adapter/cdPipelineDeploymentHistoryReq.go
  pkg/devtronResource/adapter/dataAdapters.go
  pkg/devtronResource/bean/apiReqDecoderBean.go
  pkg/devtronResource/bean/bean.go
  pkg/devtronResource/bean/commonBean.go
  pkg/devtronResource/bean/history/cdPipelineDeploymentHistory.go
  pkg/devtronResource/helper/helper.go
  pkg/devtronResource/history/deployment/cdPipeline/DeploymentHistoryService.go
  pkg/devtronResource/read/DevtronResourceSearchableKeyService.go
  pkg/devtronResource/util/commonUtil.go
  pkg/imageDigestPolicy/imageDigestPolicyService.go
  pkg/resourceGroup/ResourceGroupService.go
  pkg/resourceQualifiers/QualifierMappingService.go
  pkg/variables/ScopedVariableService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5185 feat: notifier behind nats
  client/events/EventClient.go
  client/events/event_test.go
  env_gen.md
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/blob-storage/AwsS3Blob.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/AzureBlob.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/Bean.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/BlobStorageService.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/BlobUtils.go
  vendor/github.com/devtron-labs/common-lib/blob-storage/GCPBlob.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/ProviderIdentifierService.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/bean/bean.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/alibaba.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/aws.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/azure.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/digitalOcean.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/google.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/oracle.go
  vendor/github.com/devtron-labs/common-lib/constants/constants.go
  vendor/github.com/devtron-labs/common-lib/middlewares/recovery.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/metrics/metrics.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/model/PubSubClientBean.go
  vendor/github.com/devtron-labs/common-lib/utils/CommandExecutor.go
  vendor/github.com/devtron-labs/common-lib/utils/CommonUtils.go
  vendor/github.com/devtron-labs/common-lib/utils/ErrorUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/LogProvider.go
  vendor/github.com/devtron-labs/common-lib/utils/bean/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/http/HttpUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_apiservice.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_argo.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_daemonset.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_deployment.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_hpa.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_ingress.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_job.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_pod.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_pvc.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_replicaset.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_service.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/health/health_statefulset.go
  vendor/github.com/devtron-labs/common-lib/utils/k8sObjectsUtil/DockerImageFinder.go
  vendor/github.com/devtron-labs/common-lib/utils/k8sObjectsUtil/EphemeralContainersUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8sObjectsUtil/ImageUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8sObjectsUtil/SecretUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/remoteConnection/bean/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/yaml/YamlUtil.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5193 doc: Created Resource Watcher Doc
  docs/SUMMARY.md
  docs/user-guide/resource-watcher.md
Labels: documentation, PR:Ready-to-Review

#5259 fix: latest version in default cluster and on UI
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/discover/repository/AppStoreApplicationVersionRepository.go
  pkg/appStore/discover/repository/AppStoreRepository.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5268 fix: App clone config map fix
  cmd/external-app/wire_gen.go
  pkg/appClone/AppCloneService.go
Labels: PR:Ready-to-Review

#5196 chore: email lowercase handling
  api/auth/user/UserAuthHandler.go
  go.mod
  go.sum
  internal/sql/repository/UserAttributesRepository.go
  pkg/auth/user/UserAuthService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/repository/UserRepository.go
  pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
  pkg/auth/user/util/emailUtil.go
  pkg/auth/user/util/util.go
  scripts/sql/252_email_lower_case_handling.down.sql
  scripts/sql/252_email_lower_case_handling.up.sql
  vendor/github.com/devtron-labs/authenticator/apiToken/ApiTokenSecretStore.go
  vendor/github.com/devtron-labs/authenticator/client/k8sClient.go
  vendor/github.com/devtron-labs/authenticator/client/oidcClient.go
  vendor/github.com/devtron-labs/authenticator/jwt/jwt.go
  vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go
  vendor/github.com/devtron-labs/authenticator/middleware/Config.go
  vendor/github.com/devtron-labs/authenticator/middleware/sessionmanager.go
  vendor/github.com/devtron-labs/authenticator/middleware/userLogin.go
  vendor/github.com/devtron-labs/authenticator/oidc/hhtpProxy.go
  vendor/github.com/devtron-labs/authenticator/oidc/http.go
  vendor/github.com/devtron-labs/authenticator/oidc/oidc.go
  vendor/github.com/devtron-labs/authenticator/oidc/provider.go
  vendor/github.com/devtron-labs/authenticator/oidc/templates.go
  vendor/github.com/devtron-labs/authenticator/password/password.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5178 feat: Restrict access on terminal for all non Super Admin Users
  api/k8s/application/k8sApplicationRestHandler.go
  env_gen.md
  util/GlobalConfig.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5164 fix: Vulnerability scanning on hibernate/unhibernate api's
  pkg/deployment/trigger/devtronApps/TriggerService.go
Labels: PR:Ready-to-Review

#5187 feat: tenants and installations migration
  scripts/sql/253_tenants.down.sql
  scripts/sql/253_tenants.up.sql
Labels: PR:Ready-to-Review

#5313 fix: restart workloads fix in app group
  go.mod
  pkg/deployment/manifest/deploymentTemplate/chartRef/ChartRefService.go
  pkg/generateManifest/DeploymentTemplateService.go
  pkg/generateManifest/helper.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5293 fix: Multiple choice option for namespace in Kubernetes resource permission
  cmd/external-app/wire_gen.go
  go.mod
  pkg/auth/user/UserCommonService.go
  wire_gen.go
Labels: bug, PR:Ready-to-Review

#4949 feat: Up and Down Script for BitBucket Plugin v1.0.0
  assets/bitbucket-logo-plugin.jpeg
  scripts/sql/255_bitbucket_runner_plugin.down.sql
  scripts/sql/255_bitbucket_runner_plugin.up.sql
Labels: PR:Ready-to-Review

#5319 feat: chart ref schema db migration
  scripts/sql/256_custom_deployment_schema.down.sql
  scripts/sql/256_custom_deployment_schema.up.sql
Labels: PR:Issue-verification-failed

#5183 fix: chart group rbac issue
  api/appStore/InstalledAppRestHandler.go
  pkg/appStore/chartGroup/bean.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5327 chore: updated go version in EA dockerfile
  DockerfileEA
Labels: PR:Issue-verification-failed

#5333 chore: update common-lib tag version
  go.mod
  go.sum
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5330 fix: encountering panic in application groups in build and deploy page
  api/restHandler/app/appList/AppListingRestHandler.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/pipeline/DeploymentPipelineConfigService.go
Labels: PR:Ready-to-Review

#5328 feat: insecure support for chart-sync
  api/chartRepo/ChartRepositoryRestHandler.go
  api/helm-app/gRPC/applist.pb.go
  api/helm-app/gRPC/applist.proto
  api/helm-app/service/HelmAppService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
  pkg/chartRepo/ChartRepositoryService.go
  scripts/sql/258_chart_repo_insecure_default_values.down.sql
  scripts/sql/258_chart_repo_insecure_default_values.up.sql
Labels: PR:Ready-to-Review

#5335 docs: Fixes + Corrections in Docs
  docs/FAQs/devtron-troubleshoot.md
  docs/SUMMARY.md
  docs/reference/glossary.md
  docs/user-guide/creating-application/environment-overrides.md
  docs/user-guide/creating-application/gitops-config.md
  docs/user-guide/creating-application/workflow/ci-pipeline-legacy.md
  docs/user-guide/creating-application/workflow/ci-pipeline.md
  docs/user-guide/global-configurations/git-accounts.md
  docs/user-guide/global-configurations/gitops.md
  docs/user-guide/jobs/workflow-editor-job.md
Labels: documentation, PR:Ready-to-Review

#5347 feat: mirgator plugin
  assets/plugin-golang-migrate.png
  docs/user-guide/plugins/golang-migrate.md
  scripts/sql/259_migration_plugin.down.sql
  scripts/sql/259_migration_plugin.up.sql
Labels: PR:Ready-to-Review

#5342 fix: panic issue in get/ download pod logs api
  api/k8s/application/k8sApplicationRestHandler.go
  pkg/k8s/application/k8sApplicationService.go
Labels: enhancement, PR:Ready-to-Review

#5362 docs: Added specs for the global plugin Apis
  specs/global-plugin.yaml
Labels: PR:Ready-to-Review

#5372 doc: Plugin Creation Doc
  docs/SUMMARY.md
  docs/user-guide/plugins/create-plugin.md
  docs/user-guide/plugins/plugin-list.md
Labels: documentation, PR:Ready-to-Review

#5378 doc: Redirection Issue Trial Fix
  .gitbook.yaml
Labels: PR:Ready-to-Review

#5381 doc: Redirection Fixes for 0.7
  .gitbook.yaml
Labels: PR:Ready-to-Review

#5382 doc: Redirection Fix for User Permissions Doc + Other Fixes
  .gitbook.yaml
Labels: PR:Ready-to-Review

#5383 chore: migration for gitops config
  scripts/sql/260_gitops_ssh.down.sql
  scripts/sql/260_gitops_ssh.up.sql
Labels: PR:Ready-to-Review

#5393 fix: optimised FetchLatestDeploymentWithChartRefs query
  internal/sql/repository/DeploymentTemplateRepository.go
Labels: PR:Ready-to-Review
