Repository devtron-labs/devtron, pull requests merged in 2024-07, with the labels that each got.

#5406 feat: new scripts added for rescan sbom support , helm manifest scan flag and git container links
  scripts/sql/261_alter_image_scan_execution_history.down.sql
  scripts/sql/261_alter_image_scan_execution_history.up.sql
  scripts/sql/262_alter_installed_app.down.sql
  scripts/sql/262_alter_installed_app.up.sql
  scripts/sql/263_code_scan_plugin.down.sql
  scripts/sql/263_code_scan_plugin.up.sql
  scripts/sql/264_image_scan_plugin.down.sql
  scripts/sql/264_image_scan_plugin.up.sql
Labels: PR:Ready-to-Review

#4800 doc: Created Deployment Window Draft
  docs/SUMMARY.md
  docs/user-guide/global-configurations/deployment-window.md
Labels: documentation, PR:Ready-to-Review

#5411 doc: Added migration steps for 0.6 to 0.7 upgrade
  docs/SUMMARY.md
  docs/setup/upgrade/README.md
  docs/setup/upgrade/devtron-upgrade-0.6.x-0.7.x.md
Labels: documentation, PR:Ready-to-Review

#5384 fix: Updating pr-issue-validator-script
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#5412 fix: gitops async failed for git cli mode in concurrent cases
  client/argocdServer/ArgoClientWrapperService.go
  env_gen.md
  internal/sql/repository/AppListingRepository.go
  pkg/deployment/gitOps/git/GitOperationService.go
  pkg/deployment/gitOps/git/GitOpsHelper.go
  pkg/deployment/gitOps/git/GitServiceAzure.go
  pkg/deployment/gitOps/git/GitServiceBitbucket.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/deployment/gitOps/git/GitServiceGitlab.go
  pkg/deployment/gitOps/git/commandManager/GitCliManager.go
  pkg/deployment/manifest/publish/ManifestPushService.go
Labels: enhancement, PR:Ready-to-Review

#5432 doc: Blob Storage Redirection + Other Fixes
  .gitbook.yaml
  docs/user-guide/resource-browser.md
Labels: documentation, PR:Ready-to-Review

#5436 fix: fix for terminal disconnect issue when custom transport is being used
  go.mod
  go.sum
  pkg/terminal/terminalSesion.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5445 fix: repo url and name handling with argocd
  client/argocdServer/ArgoClientWrapperService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
Labels: PR:Ready-to-Review

#5446 chore: common-lib upgrade for nats replicas
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5434 fix: empty the code and image scan script
  scripts/sql/263_code_scan_plugin.down.sql
  scripts/sql/263_code_scan_plugin.up.sql
  scripts/sql/264_image_scan_plugin.down.sql
  scripts/sql/264_image_scan_plugin.up.sql
Labels: PR:Ready-to-Review

#5443 fix: external helm app when linked to devtron and page breaks while adding project to it, without switching back to applist
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Labels: PR:Ready-to-Review

#5449 fix: override clusterRbac with direct allow behaviour for super admin
  api/k8s/application/k8sApplicationRestHandler.go
Labels: PR:Ready-to-Review

#5426 feat: updated kubelink grpc client cfg
  api/helm-app/gRPC/applicationClient.go
  api/helm-app/wire_helmApp.go
  cmd/external-app/wire_gen.go
  env_gen.md
  go.mod
  go.sum
  internal/util/ChartTemplateService.go
  internal/util/ChartTemplateService_test.go
  internal/util/mocks/ChartTemplateService.go
  pkg/appStore/installedApp/adapter/Adapter.go
  pkg/appStore/installedApp/service/common/AppStoreDeploymentCommonService.go
  pkg/chart/ChartService.go
  pkg/deployment/manifest/deploymentTemplate/DeploymentTemplateService.go
  pkg/deployment/manifest/deploymentTemplate/chartRef/ChartRefService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  scripts/devtron-reference-helm-charts/reference-chart-proxy/Chart.yaml
  vendor/github.com/devtron-labs/common-lib/utils/grpc/GrpcConfig.go
  vendor/helm.sh/helm/v3/LICENSE
  vendor/helm.sh/helm/v3/internal/sympath/walk.go
  vendor/helm.sh/helm/v3/internal/version/version.go
  vendor/helm.sh/helm/v3/pkg/chart/chart.go
  vendor/helm.sh/helm/v3/pkg/chart/dependency.go
  vendor/helm.sh/helm/v3/pkg/chart/errors.go
  vendor/helm.sh/helm/v3/pkg/chart/file.go
  vendor/helm.sh/helm/v3/pkg/chart/loader/archive.go
  vendor/helm.sh/helm/v3/pkg/chart/loader/directory.go
  vendor/helm.sh/helm/v3/pkg/chart/loader/load.go
  vendor/helm.sh/helm/v3/pkg/chart/metadata.go
  vendor/helm.sh/helm/v3/pkg/chartutil/capabilities.go
  vendor/helm.sh/helm/v3/pkg/chartutil/chartfile.go
  vendor/helm.sh/helm/v3/pkg/chartutil/coalesce.go
  vendor/helm.sh/helm/v3/pkg/chartutil/compatible.go
  vendor/helm.sh/helm/v3/pkg/chartutil/create.go
  vendor/helm.sh/helm/v3/pkg/chartutil/dependencies.go
  vendor/helm.sh/helm/v3/pkg/chartutil/doc.go
  vendor/helm.sh/helm/v3/pkg/chartutil/errors.go
  vendor/helm.sh/helm/v3/pkg/chartutil/expand.go
  vendor/helm.sh/helm/v3/pkg/chartutil/jsonschema.go
  vendor/helm.sh/helm/v3/pkg/chartutil/save.go
  vendor/helm.sh/helm/v3/pkg/chartutil/validate_name.go
  vendor/helm.sh/helm/v3/pkg/chartutil/values.go
  vendor/helm.sh/helm/v3/pkg/ignore/doc.go
  vendor/helm.sh/helm/v3/pkg/ignore/rules.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#5430 fix: compare manifest fixes
  env_gen.md
  pkg/app/AppService.go
  pkg/chart/ChartService.go
  pkg/chart/bean.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/deployment/manifest/deploymentTemplate/chartRef/ChartRefService.go
  pkg/generateManifest/DeploymentTemplateService.go
  pkg/generateManifest/bean.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5453 feat: oss-chart-changes
  charts/devtron/templates/_helpers.tpl
  charts/devtron/templates/app-sync-job.yaml
  charts/devtron/templates/dashboard.yaml
  charts/devtron/templates/devtron.yaml
  charts/devtron/templates/dex.yaml
  charts/devtron/templates/gitsensor.yaml
  charts/devtron/templates/grafana.yaml
  charts/devtron/templates/install.yaml
  charts/devtron/templates/kubelink.yaml
  charts/devtron/templates/kubewatch.yaml
  charts/devtron/templates/lens.yaml
  charts/devtron/templates/migrator.yaml
  charts/devtron/templates/minio.yaml
  charts/devtron/templates/nats-server.yaml
  charts/devtron/templates/notifier.yaml
  charts/devtron/templates/postgresql.yaml
  charts/devtron/templates/workflow.yaml
  charts/devtron/values.yaml
Labels: PR:Issue-verification-failed

#5462 fix: EA mode wire fix
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
Labels: PR:Ready-to-Review

#5431 feat: support for handling hibernation and un-hibernation for keda enabled
  pkg/deployment/deployedApp/DeployedAppService.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/deployment/manifest/helper/helper.go
Labels: PR:Ready-to-Review

#5448 feat: Async ArgoCd App refresh operation
  Wire.go
  WiringNilCheck.go
  client/argocdServer/ArgoClientWrapperService.go
  client/argocdServer/application/Application.go
  env_gen.md
  go.mod
  go.sum
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
  pkg/asyncProvider/AsyncProvider.go
  pkg/asyncProvider/wire_AsyncProvider.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  util/reflectUtil/ReflectUtil.go
  vendor/github.com/devtron-labs/common-lib/async/async.go
  vendor/github.com/devtron-labs/common-lib/constants/constants.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
  vendor/github.com/devtron-labs/common-lib/utils/runTime/GetCallerFrames.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#5358 fix: switch ci fixes
  internal/sql/repository/appWorkflow/AppWorkflowRepository.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/bean/app.go
  pkg/pipeline/BuildPipelineSwitchService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
Labels: PR:Ready-to-Review

#5461 fix: ci patch rbac fixes
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
Labels: PR:Ready-to-Review

#5497 fix: handle nil check image scanning
  api/restHandler/ImageScanRestHandler.go
Labels: PR:Ready-to-Review

#5498 fix: patch ci rbac fix
  api/restHandler/ImageScanRestHandler.go
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
  pkg/appWorkflow/AppWorkflowService.go
  pkg/bean/app.go
Labels: PR:Issue-verification-failed

#5499 fix: external ci creation fix
  pkg/pipeline/DeploymentPipelineConfigService.go
Labels: PR:Issue-verification-failed

#5501 fix: post cd auto trigger not working for helm type deployments
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
Labels: PR:Issue-verification-failed

#5502 doc: Added FAQ no. 28 + GoLang-migrate Link + Code Block Fix
  docs/FAQs/devtron-troubleshoot.md
  docs/SUMMARY.md
  docs/user-guide/global-configurations/image-promotion-policy.md
  docs/user-guide/plugins/plugin-list.md
  docs/user-guide/resource-browser.md
Labels: documentation, PR:Ready-to-Review

#5505 fix: bitbucket commit race condition for concurrent requests
  cmd/external-app/wire_gen.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppGitOpsService.go
  pkg/deployment/gitOps/git/GitOperationService.go
  pkg/deployment/gitOps/git/GitServiceBitbucket.go
  pkg/deployment/gitOps/git/models.go
  pkg/deployment/manifest/publish/ManifestPushService.go
  util/retryFunc/RetryFunction.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5481 fix: autoscale error handling
  client/argocdServer/k8sClient.go
  go.mod
  go.sum
  internal/errors/bean.go
  internal/middleware/instrument.go
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/deployment/manifest/helper/helper.go
  pkg/k8s/helper.go
  pkg/security/ImageScanService.go
  pkg/workflow/dag/WorkflowDagExecutor.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/adapter.go
  vendor/modules.txt
Labels: enhancement, PR:Ready-to-Review

#5514 feat: External Ci with Job giving run time param externalCiArtifact
  pkg/pipeline/CiService.go
Labels: PR:Ready-to-Review

#5534 feat: expose git commit data as env vars for ci stage
  pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CiMaterialConfigService.go
  pkg/pipeline/CiService.go
  pkg/pipeline/types/Workflow.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5459 docs: Drafted Software Distribution Hub
  docs/SUMMARY.md
  docs/user-guide/sdh/README.md
  docs/user-guide/sdh/release-hub.md
  docs/user-guide/sdh/tenants.md
Labels: documentation, PR:Ready-to-Review

#5523 fix: ci material update fixes for linked ci pipelines
  internal/sql/repository/pipelineConfig/CiPipelineRepository.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
Labels: PR:Ready-to-Review

#5314 doc: Created Image Label + Comments Doc
  docs/SUMMARY.md
  docs/user-guide/application-groups.md
  docs/user-guide/deploying-application/image-labels-and-comments.md
  docs/user-guide/sdh/release-hub.md
  docs/user-guide/sdh/tenants.md
Labels: PR:Ready-to-Review

#5545 doc: FAQ added for Bitnami Charts
  docs/FAQs/devtron-troubleshoot.md
Labels: PR:Ready-to-Review

#5522 fix: Unable to get HPA manifest for no-gitops deployment
  api/helm-app/service/HelmAppService.go
  cmd/external-app/wire_gen.go
  go.mod
  go.sum
  pkg/argoApplication/ArgoApplicationService.go
  pkg/chartRepo/ChartRepositoryService.go
  pkg/cluster/ClusterService.go
  pkg/cluster/EnvironmentService.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/dockerRegistry/DockerRegistryIpsConfigService.go
  pkg/gitops/GitOpsConfigService.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/capacity/k8sCapacityService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/terminal/terminalSesion.go
  vendor/github.com/devtron-labs/common-lib/constants/constants.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#5526 fix: Deployment stuck in starting for no-gitops based pipelines
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
Labels: enhancement, PR:Ready-to-Review

#5541 fix: panic handling for deleted app in app group and env group filters
  pkg/resourceGroup/ResourceGroupService.go
Labels: PR:Ready-to-Review

#5549 fix: security time fix when scanning is passed
  internal/sql/repository/security/ImageScanHistoryRepository.go
  pkg/security/ImageScanService.go
Labels: PR:Ready-to-Review

#5489 feat: Feature release v5
  scripts/sql/267_release_track_deps.down.sql
  scripts/sql/267_release_track_deps.up.sql
Labels: PR:Ready-to-Review

#5420 feat: gitlab webhook queries
  api/restHandler/GitHostRestHandler.go
  api/restHandler/WebhookEventHandler.go
  client/gitSensor/GitSensorGrpcClient.go
  client/gitSensor/GitSensorRestClient.go
  go.mod
  go.sum
  internal/sql/repository/GitHostRepository.go
  pkg/auth/authorisation/casbin/rbac_test.go
  pkg/eventProcessor/out/CIPipelineEventPublishService.go
  pkg/eventProcessor/out/bean/bean.go
  pkg/pipeline/GitHostConfig.go
  pkg/pipeline/WebhookEventDataConfig.go
  scripts/sql/268_gitlab_webhook.down.sql
  scripts/sql/268_gitlab_webhook.up.sql
  util/helper.go
  vendor/github.com/devtron-labs/protos/gitSensor/service.pb.go
  vendor/github.com/devtron-labs/protos/gitSensor/service.proto
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#5307 feat: feature flag BuildxCacheModeMin and AsyncBuildxCacheExport
  env_gen.md
  pkg/pipeline/CiService.go
  pkg/pipeline/types/Workflow.go
Labels: PR:Ready-to-Review

#5558 fix: query optimisations
  internal/sql/repository/CustomTagRepository.go
  internal/sql/repository/deploymentConfig/repository.go
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
  pkg/chart/ChartService.go
  pkg/deployment/common/deploymentConfigService.go
  pkg/deployment/gitOps/config/GitOpsConfigReadService.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/CustomTagService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/bean/CustomTagService.go
Labels: enhancement, PR:Ready-to-Review

#5571 doc: Added Keycloak SSO Doc
  .gitbook.yaml
  docs/SUMMARY.md
  docs/user-guide/global-configurations/authorization/sso/keycloak.md
  docs/user-guide/global-configurations/authorization/sso/oidc.md
  docs/user-guide/global-configurations/authorization/sso/okta.md
Labels: PR:Ready-to-Review

#5552 fix: version and fixed_version in image scan result table
  internal/sql/repository/security/ImageScanResultRepository.go
  pkg/security/ImageScanService.go
  scripts/sql/268_gitlab_webhook.up.sql
  scripts/sql/269_alter_image_scan_execution_result_.down.sql
  scripts/sql/269_alter_image_scan_execution_result_.up.sql
Labels: PR:Ready-to-Review

#5565 misc: bug fix for picking wrong values in docker arguments
  pkg/pipeline/CiService.go
Labels: PR:Ready-to-Review

#5579 fix: add if not exists in migration script for avoiding any errors while rerunning scripts
  scripts/sql/269_alter_image_scan_execution_result_.down.sql
  scripts/sql/269_alter_image_scan_execution_result_.up.sql
Labels: PR:Ready-to-Review

#5585 feat: ext argo router in ea mode
  cmd/external-app/router.go
  cmd/external-app/wire_gen.go
  env_gen.md
Labels: PR:Ready-to-Review

#5352 feat: plugin versioning feature
  api/restHandler/GlobalPluginRestHandler.go
  api/restHandler/app/pipeline/configure/DeploymentPipelineRestHandler.go
  api/restHandler/common/ParamParserUtils.go
  api/router/GlobalPluginRouter.go
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
  pkg/pipeline/CiService.go
  pkg/pipeline/PipelineStageService.go
  pkg/pipeline/pipelineStageVariableParser.go
  pkg/pipeline/types/Workflow.go
  pkg/plugin/GlobalPluginService.go
  pkg/plugin/bean/bean.go
  pkg/plugin/helper/helper.go
  pkg/plugin/repository/GlobalPluginRepository.go
  pkg/plugin/utils.go
  pkg/plugin/utils/utils.go
  scripts/sql/270_plugin_parent_metadata.down.sql
  scripts/sql/270_plugin_parent_metadata.up.sql
  scripts/sql/271_alter_plugin_metadata.down.sql
  scripts/sql/271_alter_plugin_metadata.up.sql
  specs/plugin/plugin-creation.yaml
  wire_gen.go
Labels: PR:Ready-to-Review

#5584 feat: service account in chart sync
  pkg/chartRepo/ChartRepositoryService.go
  pkg/chartRepo/ManualAppSyncYaml.go
  pkg/server/config/ServerEnvConfig.go
Labels: PR:Ready-to-Review

#5570 fix: ArgoCD Vulnerable to Use of Risky or Missing Cryptographic Algorithms in Redis Cache
  go.mod
  go.sum
  vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/generated.proto
  vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/openapi_generated.go
  vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/types.go
  vendor/github.com/skeema/knownhosts/NOTICE
  vendor/github.com/skeema/knownhosts/README.md
  vendor/github.com/skeema/knownhosts/knownhosts.go
  vendor/modules.txt
Labels: enhancement, PR:Issue-verification-failed

#5591 doc: Collated Doc Fixes for July
  .gitbook.yaml
  docs/user-guide/deploying-application/image-labels-and-comments.md
  docs/user-guide/global-configurations/README.md
  docs/user-guide/plugins/plugin-list.md
  docs/user-guide/resource-browser.md
  docs/user-guide/sdh/tenants.md
Labels: documentation, PR:Ready-to-Review

#5533 doc: Drafted Schema Driven DT
  docs/user-guide/creating-application/deployment-template.md
  docs/user-guide/creating-application/deployment-template/deployment.md
  docs/user-guide/creating-application/deployment-template/rollout-deployment.md
  docs/user-guide/creating-application/environment-overrides.md
Labels: documentation, PR:Ready-to-Review

#5573 fix: resource-browser-shortnames
  env_gen.md
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review
