Repository devtron-labs/devtron, pull requests merged in 2024-04, with the labels that each got.

#4856 misc: Refactoring Pagerduty Issue Calculator script
  .github/CODEOWNERS
  scripts/utilities/github_pagerduty_issue_score_calculation.py
Labels: PR:Ready-to-Review

#4836 feat: Add support for git hash in the app and app group overview section _revised
  api/bean/AppView.go
  internal/sql/repository/AppListingRepository.go
  pkg/app/AppListingService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4857 fix: return nil,err on git material fetch error
  pkg/pipeline/CiHandler.go
Labels: PR:Ready-to-Review

#4838 fix: removed code for gitops repo migration in devtron apps
  pkg/app/ManifestPushService.go
  pkg/app/bean/ManifestPushTemplate.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
Labels: PR:Ready-to-Review

#4876 fix: update argo app repo url in patch
  client/argocdServer/ArgoClientWrapperService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
Labels: PR:Ready-to-Review

#4875 fix: injected app-serveice dependency into DeployedApplicationEventProcessor service
  pkg/eventProcessor/in/DeployedApplicationEventProcessorService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4631 fix: chart sync job optimisation
  pkg/chartRepo/ChartRepositoryService.go
Labels: PR:Ready-to-Review

#4892 fix: use join cookie logic to extract token
  go.mod
  go.sum
  vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go
  vendor/github.com/devtron-labs/authenticator/oidc/oidc.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4840 fix: rbac fix in case of project in upper case
  api/restHandler/app/workflow/AppWorkflowRestHandler.go
  util/rbac/EnforcerUtil.go
Labels: PR:Ready-to-Review

#4896 fix: deprecate latest in app store app version
  pkg/appStore/discover/repository/AppStoreApplicationVersionRepository.go
  scripts/sql/235_app_atore_application.down.sql
  scripts/sql/235_app_store_application_version.up.sql
Labels: PR:Ready-to-Review

#4906 chore: migration support for notification db changes
  internal/sql/repository/NotificationSettingsRepository.go
  internal/sql/repository/WebhookNotificationRepository.go
  pkg/notifier/WebhookNotificationService.go
  pkg/notifier/WebhookNotificationService_test.go
  scripts/sql/236_image_scan_notification.down.sql
  scripts/sql/236_image_scan_notification.up.sql
Labels: enhancement, PR:Ready-to-Review

#4908 feat: Added the Devtron CI Trigger Plugin
  scripts/sql/237_devtron_ci_trigger_plugin.down.sql
  scripts/sql/237_devtron_ci_trigger_plugin.up.sql
Labels: PR:Ready-to-Review

#4841 fix:duplicate workflow name fixed
  api/restHandler/CoreAppRestHandler.go
  pkg/appWorkflow/AppWorkflowService.go
  util/helper.go
Labels: PR:Ready-to-Review

#4863 fix:job name support added in input variables
  api/restHandler/GlobalPluginRestHandler.go
  pkg/pipeline/CiService.go
  pkg/plugin/GlobalPluginService.go
Labels: PR:Ready-to-Review

#4911 fix: Corrected the error of fetching app name and pipeline name from CI_CD_EVENT
  scripts/sql/237_devtron_ci_trigger_plugin.up.sql
Labels: PR:Ready-to-Review

#4919 fix: link external helm app to chart store
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
Labels: PR:Ready-to-Review

#4909 perf: memory optimizations and prom metrics on terminal session exposed
  client/events/EventClient.go
  internal/middleware/instrument.go
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/k8s/K8sCommonService.go
  pkg/terminal/constants.go
  pkg/terminal/terminalSesion.go
Labels: PR:Ready-to-Review

#4928 fix: release not found alert
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
Labels: PR:Ready-to-Review

#4916 fix: removed unused dependency
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
Labels: PR:Ready-to-Review

#4930 chore: Expose Global Container Registry Configuration for All Microservices in Devtron Helm Chart
  charts/devtron/devtron-bom.yaml
  charts/devtron/templates/_helpers.tpl
  charts/devtron/templates/app-sync-job.yaml
  charts/devtron/templates/dashboard.yaml
  charts/devtron/templates/devtron.yaml
  charts/devtron/templates/dex.yaml
  charts/devtron/templates/gitsensor.yaml
  charts/devtron/templates/grafana.yaml
  charts/devtron/templates/install.yaml
  charts/devtron/templates/kubelink.yaml
  charts/devtron/templates/kubewatch.yaml
  charts/devtron/templates/lens.yaml
  charts/devtron/templates/migrator.yaml
  charts/devtron/templates/minio.yaml
  charts/devtron/templates/nats-server.yaml
  charts/devtron/templates/notifier.yaml
  charts/devtron/templates/postgresql.yaml
  charts/devtron/templates/workflow.yaml
  charts/devtron/values.yaml
Labels: PR:Issue-verification-failed

#4963 fix: helm secret default value
  api/helm-app/service/HelmAppService.go
Labels: PR:Ready-to-Review

#4941 fix: dependabot version upgrade
  go.mod
  go.sum
  vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/applicationset_types.go
  vendor/github.com/argoproj/argo-cd/v2/pkg/apis/application/v1alpha1/generated.proto
  vendor/github.com/argoproj/argo-cd/v2/util/helm/client.go
Labels: PR:Ready-to-Review

#4967 fix: dependabot version upgrade
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4895 doc: Added User-defined Git Repo
  docs/SUMMARY.md
  docs/user-guide/cloning-application.md
  docs/user-guide/creating-application/README.md
  docs/user-guide/creating-application/gitops-config.md
  docs/user-guide/creating-application/workflow/cd-pipeline.md
  docs/user-guide/global-configurations/gitops.md
Labels: documentation, PR:Ready-to-Review

#4937 feat: added fields in app details api
  api/bean/AppView.go
  internal/sql/repository/AppListingRepository.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4935 feat: fetch cluster name
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Labels: PR:Ready-to-Review

#4912 fix: fix for gitops repo url configured in argocd and stored in db are out of sync, then 3 commits are being done
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppGitOpsService.go
  pkg/deployment/gitOps/git/GitOperationService.go
Labels: PR:Ready-to-Review

#4961 feat: all env at one place
  Makefile
  env_gen.md
  fetchAllEnv/fetchAllEnv.go
Labels: PR:Ready-to-Review

#4947 fix: latest flag dependency removed
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/discover/repository/AppStoreApplicationVersionRepository.go
  pkg/appStore/discover/service/AppStoreService.go
Labels: PR:Issue-verification-failed

#4931 fix: ci-cd count per day in telemetry data
  client/telemetry/TelemetryEventClientExtended.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/GitOpsConfigRepository.go
  internal/sql/repository/GitProviderRepository.go
  internal/sql/repository/dockerRegistry/DockerArtifactStoreRepository.go
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
  internal/sql/repository/pipelineConfig/CiPipelineRepository.go
  internal/sql/repository/pipelineConfig/CiWorkflowRepository.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/cluster/EnvironmentService.go
  pkg/cluster/repository/EnvironmentRepository.go
  pkg/deployment/gitOps/config/GitOpsConfigReadService.go
  wire_gen.go
Labels: bug, PR:Ready-to-Review

#4992 feat: image promotion migration
  scripts/casbin/8_artifact_promoter.down.sql
  scripts/casbin/8_artifact_promoter.up.sql
  scripts/sql/238_artifacts_promotion.down.sql
  scripts/sql/238_artifacts_promotion.up.sql
Labels: PR:Ready-to-Review

#4994 fix: image-approval-migartion fix
  scripts/sql/238_artifacts_promotion.up.sql
Labels: PR:Ready-to-Review

#4996 fix: image promotion sql script
  scripts/sql/238_artifacts_promotion.down.sql
  scripts/sql/238_artifacts_promotion.up.sql
Labels: PR:Ready-to-Review

#4991 doc: Added Linked CI with Child Info + Runtime Build Parameters
  docs/user-guide/application-groups.md
  docs/user-guide/creating-application/workflow/ci-pipeline.md
  docs/user-guide/deploying-application/triggering-ci.md
Labels: documentation, PR:Ready-to-Review

#5004 fix: removed redundant import
  pkg/variables/ScopedVariableService.go
Labels: PR:Ready-to-Review

#4980 fix: grpc error handling for TemplateChart req
  api/helm-app/service/HelmAppService.go
  pkg/generateManifest/DeployementTemplateService.go
Labels: PR:Ready-to-Review

#4946 fix: terminate sync if in progress
  client/argocdServer/ArgoClientWrapperService.go
  client/argocdServer/application/Application.go
  pkg/app/AppService.go
  pkg/app/ManifestPushService.go
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/workflow/status/WorkflowStatusService.go
Labels: PR:Ready-to-Review

#5012 fix: Kubelink Requests getting Failed for gRPC method GetAppDetails
  api/restHandler/app/appList/AppListingRestHandler.go
Labels: PR:Ready-to-Review

#4978 fix: deleted api token can be reused if created again with same name
  pkg/apiToken/ApiTokenBean.go
  pkg/apiToken/ApiTokenRepository.go
  pkg/apiToken/ApiTokenService.go
  pkg/auth/user/UserAuthService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/bean/bean.go
  pkg/auth/user/helper/helper.go
  pkg/auth/user/repository/UserRepository.go
  scripts/sql/239_api_token_version_support.down.sql
  scripts/sql/239_api_token_version_support.up.sql
Labels: PR:Ready-to-Review

#4862 feat: Introduction to feasibility in Deployment
  internal/constants/InternalErrorCode.go
  pkg/cluster/EnvironmentService.go
  pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/deployment/trigger/devtronApps/adapter/adapter.go
  pkg/deployment/trigger/devtronApps/bean/bean.go
  pkg/deployment/trigger/devtronApps/feasibilityChecker.go
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
  pkg/security/ImageScanService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5024 doc: Changes made in the doc according to the newer version
  docs/user-guide/plugins/sonarqube-v1.1.0.md
Labels: PR:Ready-to-Review

#5005 fix: application status changes to HIBERNATING, when hibernation fails due to some reason
  pkg/app/AppListingService.go
Labels: PR:Ready-to-Review

#5022 fix: Dockerfile ubuntu version
  Dockerfile
  DockerfileEA
Labels: PR:Ready-to-Review

#5029 doc: Added new doc in the index
  docs/SUMMARY.md
Labels: PR:Ready-to-Review

#5016 fix: handle for wrong format of k8s version in semvercompare func in cronjob template charts
  api/helm-app/gRPC/applist.pb.go
  api/helm-app/gRPC/applist.proto
  api/helm-app/service/HelmAppService.go
  env_gen.md
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/deployment/trigger/devtronApps/bean/bean.go
  pkg/generateManifest/DeployementTemplateService.go
  pkg/k8s/helper.go
  pkg/k8s/helper_test.go
  wire_gen.go
Labels: PR:Ready-to-Review
