Repository devtron-labs/devtron, pull requests merged in 2024-08, with the labels that each got.

#5603 feat: panic in sync pod cron and terminal not opening fix
  pkg/k8s/K8sCommonService.go
  pkg/k8s/capacity/k8sCapacityService.go
Labels: PR:Ready-to-Review

#5609 fix: tls enabled flag not getting passed
  pkg/deployment/gitOps/git/GitFactory.go
  pkg/deployment/gitOps/git/GitOpsHelper.go
  pkg/deployment/gitOps/git/commandManager/bean.go
Labels: PR:Ready-to-Review

#5615 misc: added action for discrod webhook
  .github/workflows/github_pagerduty_score_calculation.yml
Labels: PR:Ready-to-Review

#5619 misc: Revert "misc: added action for discrod webhook"
  .github/workflows/github_pagerduty_score_calculation.yml
Labels: PR:Ready-to-Review

#5637 feat: system network controller sql script
  scripts/sql/273_system_controller.down.sql
  scripts/sql/273_system_controller.up.sql
Labels: PR:Ready-to-Review

#5641 fix: query optimisations for app group cd listing and ci pipeline blockage state
  api/restHandler/app/workflow/AppWorkflowRestHandler.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/deploymentConfig/repository.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/appWorkflow/AppWorkflowService.go
  pkg/chart/ChartService.go
  pkg/deployment/common/bean/bean.go
  pkg/deployment/common/deploymentConfigService.go
  pkg/pipeline/AppDeploymentTypeChangeManager.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/PipelineStageService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5646 feat: skip argowf logs from ci logs
  api/restHandler/app/pipeline/configure/PipelineConfigRestHandler.go
Labels: PR:Ready-to-Review

#5577 feat: gitops support for oci repositories
  Wire.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  go.mod
  go.sum
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppGitOpsService.go
  pkg/appStore/installedApp/service/common/AppStoreDeploymentCommonService.go
  pkg/appStore/installedApp/service/common/ociRepo_test.go
  pkg/argoRepositoryCreds/bean/bean.go
  pkg/argoRepositoryCreds/repositorySecretCreationService.go
  pkg/argoRepositoryCreds/tests/ociSecret_test.go
  pkg/chartRepo/ChartRepositoryService.go
  pkg/chartRepo/ManualAppSyncYaml.go
  pkg/pipeline/DockerRegistryConfig.go
  pkg/server/config/ServerEnvConfig.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#5528 feat: ext argo app rbac and missing common features
  Wire.go
  api/fluxApplication/FluxApplicationRestHandler.go
  api/fluxApplication/FluxApplicationRouter.go
  api/fluxApplication/wire_fluxApplication.go
  api/helm-app/HelmAppRestHandler.go
  api/helm-app/HelmAppRouter.go
  api/helm-app/gRPC/applicationClient.go
  api/helm-app/gRPC/applist.pb.go
  api/helm-app/gRPC/applist.proto
  api/helm-app/gRPC/applist_grpc.pb.go
  api/helm-app/service/HelmAppService.go
  api/helm-app/service/helper.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/k8s/application/k8sApplicationRouter.go
  api/restHandler/app/appList/AppListingRestHandler.go
  api/router/router.go
  cmd/external-app/router.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
  pkg/argoApplication/ArgoApplicationService.go
  pkg/argoApplication/bean/bean.go
  pkg/argoApplication/helper.go
  pkg/fluxApplication/FluxApplicationService.go
  pkg/fluxApplication/bean/bean.go
  pkg/fluxApplication/helper.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/application/bean/bean.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/bean.go
  pkg/k8s/helper.go
  specs/fluxcd_app.yaml
  wire_gen.go
Labels: PR:Ready-to-Review

#5582 feat: expose git ops metrics
  pkg/deployment/gitOps/git/GitServiceAzure.go
  pkg/deployment/gitOps/git/GitServiceBitbucket.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/deployment/gitOps/git/GitServiceGitlab.go
Labels: PR:Ready-to-Review

#5661 chore: Plugin script fix oss
  scripts/sql/270_plugin_parent_metadata.down.sql
  scripts/sql/271_alter_plugin_metadata.down.sql
  scripts/sql/274_improved_image_scan_plugin.down.sql
  scripts/sql/274_improved_image_scan_plugin.up.sql
Labels: PR:Ready-to-Review

#5626 feat: Generate config and secret hash for application mounting external k8s secrets
  api/bean/ConfigMapAndSecret.go
  go.mod
  go.sum
  pkg/bean/app.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/deployment/manifest/bean/bean.go
  pkg/deployment/manifest/helper/helper.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/bean.go
  pkg/k8s/helper.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5668 fix: default PipelineType given
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/bean/CiPipeline/CiBuildConfig.go
Labels: PR:Ready-to-Review

#5669 fix: validation in CiJob for external Artifact
  pkg/pipeline/CiService.go
Labels: PR:Ready-to-Review

#5670 fix: nil check for ciBaseBuildConfigBean
  pkg/pipeline/CiService.go
Labels: PR:Ready-to-Review

#5675 fix: updated common lib
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5671 fix: for concurrent read and write and in buildInformerAndNamespaceList
  pkg/k8s/informer/K8sInformerFactory.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5666 fix: handling for HPA (autoscaling)
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
Labels: PR:Ready-to-Review

#5682 chore: added config sql script
  scripts/sql/275_policy_criteria_table.down.sql
  scripts/sql/275_policy_criteria_table.up.sql
Labels: PR:Issue-verification-failed

#5685 fix: notes api for oci gitops flow
  pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
  pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
Labels: PR:Issue-verification-failed

#5687 misc: Release candidate v0.16.0
  pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
  pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
  pkg/deployment/gitOps/config/GitOpsConfigReadService.go
  pkg/deployment/gitOps/git/commandManager/GitCliManager.go
  pkg/deployment/gitOps/git/commandManager/GitCommandBaseManager.go
  scripts/sql/275_policy_criteria_table.down.sql
  scripts/sql/275_policy_criteria_table.up.sql
  util/HttpUtil.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5692 chore: migration number changes
  scripts/sql/270_improved_image_scan_plugin.down.sql
  scripts/sql/270_improved_image_scan_plugin.up.sql
  scripts/sql/271_plugin_parent_metadata.down.sql
  scripts/sql/271_plugin_parent_metadata.up.sql
  scripts/sql/272_alter_plugin_metadata.down.sql
  scripts/sql/272_alter_plugin_metadata.up.sql
  scripts/sql/273_tls_support_in_git.down.sql
  scripts/sql/273_tls_support_in_git.up.sql
  scripts/sql/274_system_controller.down.sql
  scripts/sql/274_system_controller.up.sql
Labels: PR:Ready-to-Review

#5696 fix: refrain from checkin autoscalingCheckBeforeTrigger for virt clus
  pkg/deployment/manifest/ManifestCreationService.go
Labels: PR:Ready-to-Review

#5695 fix: Decode secret fix on add update oss
  cmd/external-app/wire_gen.go
  pkg/pipeline/ConfigMapService.go
  util/encoding-utils.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5688 fix: saving pco concurrency case handled
  internal/sql/repository/chartConfig/PipelineOverrideRepository.go
  pkg/deployment/manifest/ManifestCreationService.go
Labels: PR:Ready-to-Review

#5617 feat: CVE severity categorisation and scan result listing API enhancements
  api/restHandler/ImageScanRestHandler.go
  api/restHandler/PolicyRestHandler.go
  internal/sql/repository/security/CvePolicyControle.go
  internal/sql/repository/security/CveStoreRepository.go
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
  internal/sql/repository/security/bean/bean.go
  pkg/security/ImageScanService.go
  pkg/security/bean/bean.go
  pkg/security/policyService.go
  scripts/sql/276_scan_policies.down.sql
  scripts/sql/276_scan_policies.up.sql
Labels: PR:Ready-to-Review

#5701 fix: script for pipelineStageStepVariable, making input value and default_value text from varchar255
  pkg/deployment/gitOps/git/GitOpsHelper.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/deployment/gitOps/git/commandManager/GitCliManager.go
  pkg/deployment/gitOps/git/commandManager/GoGitSdkManager.go
  scripts/sql/276_alter_pipeline_stage_step_variable.down.sql
  scripts/sql/276_alter_pipeline_stage_step_variable.up.sql
Labels: PR:Ready-to-Review

#5488 feat: Config diff phase 2 oss
  Wire.go
  api/restHandler/DeploymentConfigurationRestHandler.go
  api/router/DeploymentConfigRouter.go
  api/router/router.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/app/AppRepository.go
  internal/sql/repository/chartConfig/ConfigMapRepository.go
  internal/sql/repository/chartConfig/PipelineOverrideRepository.go
  pkg/cluster/repository/EnvironmentRepository.go
  pkg/configDiff/DeploymentConfigurationService.go
  pkg/configDiff/adaptor/adaptor.go
  pkg/configDiff/bean/bean.go
  pkg/configDiff/helper/helper.go
  pkg/configDiff/utils/utils.go
  pkg/deployment/gitOps/git/GitOpsHelper.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/deployment/gitOps/git/commandManager/GitCliManager.go
  pkg/deployment/gitOps/git/commandManager/GoGitSdkManager.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/pipeline/ConfigMapService.go
  pkg/pipeline/bean/ConfigMapBean.go
  pkg/plugin/bean/bean.go
  scripts/sql/270_improved_image_scan_plugin.down.sql
  scripts/sql/270_improved_image_scan_plugin.up.sql
  scripts/sql/271_plugin_parent_metadata.down.sql
  scripts/sql/271_plugin_parent_metadata.up.sql
  scripts/sql/272_alter_plugin_metadata.down.sql
  scripts/sql/272_alter_plugin_metadata.up.sql
  scripts/sql/273_tls_support_in_git.down.sql
  scripts/sql/273_tls_support_in_git.up.sql
  scripts/sql/274_system_controller.down.sql
  scripts/sql/274_system_controller.up.sql
  scripts/sql/276_alter_pipeline_stage_step_variable.down.sql
  scripts/sql/276_alter_pipeline_stage_step_variable.up.sql
  scripts/sql/277_scan_policies.down.sql
  scripts/sql/277_scan_policies.up.sql
  scripts/sql/278_rbac_role_audit.down.sql
  scripts/sql/278_rbac_role_audit.up.sql
  specs/configDiffView.yaml
  util/encoding-utils.go
  util/rbac/EnforcerUtil.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5708 fix: ea fixes for helm app
  pkg/app/AppCrudOperationService.go
  pkg/app/helper.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Labels: PR:Ready-to-Review

#5652 fix: Helm apps entries in Ea mode
  pkg/app/AppCrudOperationService.go
  pkg/app/helper.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5713 chore: ea fixes for helm app
  pkg/app/AppCrudOperationService.go
  pkg/app/helper.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Labels: PR:Ready-to-Review

#5712 fix: SkipCiBuildCachePushPull code incorporated with minor refac in handle runtime params validation
  env_gen.md
  pkg/pipeline/CiService.go
  pkg/pipeline/bean/CiPipeline/CiBuildConfig.go
  pkg/pipeline/types/CiCdConfig.go
Labels: PR:Ready-to-Review

#5718 fix: migration syn with ent
  scripts/sql/277_insert_devtron_resource_searchable_key_table.down.sql
  scripts/sql/277_insert_devtron_resource_searchable_key_table.up.sql
Labels: PR:Ready-to-Review

#5680 fix: group image vulnerabilities by base/os image
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
  internal/sql/repository/security/ImageScanResultRepository.go
  pkg/security/ImageScanService.go
  pkg/security/bean/bean.go
  scripts/sql/276_scan_policies.down.sql
  scripts/sql/276_scan_policies.up.sql
  scripts/sql/280_link_external_release.down.sql
  scripts/sql/280_link_external_release.up.sql
  scripts/sql/281_update_scan_tool_metadata.down.sql
  scripts/sql/281_update_scan_tool_metadata.up.sql
  wire_gen.go
Labels: PR:Issue-verification-failed

#5735 doc: Edit Deployment Chart Schema
  .gitbook.yaml
  docs/SUMMARY.md
  docs/reference/glossary.md
  docs/user-guide/creating-application/deployment-template.md
  docs/user-guide/global-configurations/README.md
  docs/user-guide/global-configurations/deployment-charts.md
Labels: documentation, PR:Ready-to-Review

#5360 docs: added Documentation for Air-Gapped Installation
  devtron-images.txt.source
  docs/SUMMARY.md
  docs/setup/install/install-devtron-in-airgapped-environment.md
Labels: PR:Ready-to-Review

#5739 feat: ServiceAccount Addition and Create ImagePullSecrets Function
  charts/devtron/Chart.yaml
  charts/devtron/devtron-bom.yaml
  charts/devtron/templates/_helpers.tpl
  charts/devtron/templates/app-sync-job.yaml
  charts/devtron/templates/casbin.yaml
  charts/devtron/templates/configmap-secret.yaml
  charts/devtron/templates/dashboard.yaml
  charts/devtron/templates/devtron-scc.yaml
  charts/devtron/templates/devtron.yaml
  charts/devtron/templates/dex.yaml
  charts/devtron/templates/gitsensor.yaml
  charts/devtron/templates/grafana.yaml
  charts/devtron/templates/install.yaml
  charts/devtron/templates/kubelink.yaml
  charts/devtron/templates/kubewatch.yaml
  charts/devtron/templates/lens.yaml
  charts/devtron/templates/migrator.yaml
  charts/devtron/templates/minio.yaml
  charts/devtron/templates/nats-server.yaml
  charts/devtron/templates/notifier.yaml
  charts/devtron/templates/postgresql.yaml
  charts/devtron/templates/scoop.yaml
  charts/devtron/templates/workflow.yaml
  charts/devtron/values.yaml
Labels: PR:Issue-verification-failed

#5744 feat: Env description handling
  env_gen.md
  fetchAllEnv/fetchAllEnv.go
  pkg/sql/connection.go
Labels: PR:Ready-to-Review

#5750 fix: Validate config cm cs
  pkg/pipeline/ConfigMapService.go
Labels: PR:Issue-verification-failed

#5759 fix: ci patch rbac for branch update
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
  pkg/bean/app.go
Labels: PR:Ready-to-Review

#5740 fix: Bitnami chart repo tls issue
  scripts/sql/282_bitnami_chart_fix.down.sql
  scripts/sql/282_bitnami_chart_fix.up.sql
Labels: PR:Ready-to-Review

#5771 fix: scan tool active check removed
  scripts/sql/281_update_scan_tool_metadata.down.sql
  scripts/sql/281_update_scan_tool_metadata.up.sql
Labels: PR:Ready-to-Review

#5767 feat: Docker pull env driven
  env_gen.md
  pkg/pipeline/CiService.go
  pkg/pipeline/types/CiCdConfig.go
  pkg/pipeline/types/Workflow.go
Labels: PR:Ready-to-Review

#5770 fix: panic handlings and argocd app delete stuck in partial stage
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiLogService.go
  util/helper.go
Labels: PR:Ready-to-Review
