Repository devtron-labs/devtron, pull requests merged in 2024-02, with the labels that each got.

#3708 fix: new api added for getting ciPipelineDetails by only ciPipelineId for CLI
  api/restHandler/app/BuildPipelineRestHandler.go
  api/router/PipelineConfigRouter.go
  pkg/bean/app.go
Labels: PR:Ready-to-Review

#4613 fix: resource tree bad gateway handle
  client/argocdServer/application/Application.go
Labels: PR:Ready-to-Review

#4628 chore: clean appListing api
  api/restHandler/AppListingRestHandler.go
  api/router/AppListingRouter.go
  internal/sql/repository/AppListingRepository.go
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
  pkg/app/AppListingService.go
Labels: PR:Ready-to-Review

#4349 doc: Revamped Security Feature Doc
  docs/SUMMARY.md
  docs/user-guide/security-features.md
  docs/user-guide/security-features/security-policies.md
  docs/user-guide/security-features/security-scans.md
Labels: PR:Ready-to-Review

#4539 feat: added support for downloading pod logs
  api/k8s/application/k8sApplicationRestHandler.go
  api/k8s/application/k8sApplicationRouter.go
  api/restHandler/common/ApiResponseWriter.go
  go.mod
  go.sum
  pkg/k8s/application/bean/bean.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4630 chore: Update CODEOWNERS
  .github/CODEOWNERS
Labels: PR:Ready-to-Review

#4622 feat: added support for multiple gitops configurations on shared clusters
  pkg/gitops/GitOpsConfigService.go
  pkg/util/TokenCache.go
  util/argo/ArgoUserService.go
Labels: PR:Ready-to-Review

#4589 feat: active inactive user phase 1
  api/auth/user/UserRestHandler.go
  api/auth/user/UserRouter.go
  api/auth/user/wire_user.go
  api/bean/UserRequest.go
  cmd/external-app/wire_gen.go
  internal/util/ValidateUtil.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserAuditService.go
  pkg/auth/user/UserAuthService.go
  pkg/auth/user/UserCommonService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/adapter/adapter.go
  pkg/auth/user/bean/bean.go
  pkg/auth/user/helper/helper.go
  pkg/auth/user/repository/RoleGroupRepository.go
  pkg/auth/user/repository/UserRepository.go
  pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
  scripts/sql/222_user_status.down.sql
  scripts/sql/222_user_status.up.sql
  specs/group_policy.yaml
  specs/user_policy.yaml
  wire_gen.go
Labels: PR:Ready-to-Review

#4652 feat: added proxy in github transport
  pkg/deployment/gitOps/git/GitServiceGithub.go
Labels: PR:Ready-to-Review

#4654 fix: chartRef fetch in historical deployment triggers
  internal/sql/repository/DeploymentTemplateRepository.go
  pkg/pipeline/WorkflowDagExecutor.go
Labels: PR:Ready-to-Review

#4641 fix: resource terminal update api
  api/k8s/application/k8sApplicationRestHandler.go
  api/k8s/capacity/k8sCapacityRestHandler.go
  go.mod
  go.sum
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/bean.go
  pkg/k8s/capacity/k8sCapacityService.go
  pkg/k8s/helper.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4583 feat: support build infra configurations properties configurable from ui
  Wire.go
  api/infraConfig/restHandler.go
  api/infraConfig/router.go
  api/router/router.go
  internal/sql/repository/app/AppRepository.go
  pkg/app/AppService.go
  pkg/infraConfig/bean.go
  pkg/infraConfig/constants.go
  pkg/infraConfig/infraConfigRepository.go
  pkg/infraConfig/infraConfigService.go
  pkg/infraConfig/units/units.go
  pkg/infraConfig/units/units_test.go
  pkg/infraConfig/utils.go
  pkg/pipeline/CiService.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/infraProviders/InfraProvider.go
  pkg/pipeline/infraProviders/infraGetters/ciPipeline/ciPipelineInfraGetter.go
  pkg/pipeline/infraProviders/infraGetters/infraGetter.go
  pkg/pipeline/infraProviders/infraGetters/job/jobInfraGetter.go
  pkg/pipeline/types/CiCdConfig.go
  pkg/pipeline/types/Workflow.go
  pkg/resourceQualifiers/ResourceQualifiersMappingDto.go
  scripts/sql/223_infra_configuration.down.sql
  scripts/sql/223_infra_configuration.up.sql
  specs/buildInfraConfig/build-infra-config.yaml
  util/TypeUtils.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4643 feat: added support for external argocd apps
  Wire.go
  api/argoApplication/ArgoApplicationRestHandler.go
  api/argoApplication/ArgoApplicationRouter.go
  api/argoApplication/wire_argoApplication.go
  api/helm-app/gRPC/applicationClient.go
  api/helm-app/gRPC/applist.pb.go
  api/helm-app/gRPC/applist.proto
  api/helm-app/gRPC/applist_grpc.pb.go
  api/helm-app/service/HelmAppService.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/router/router.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  pkg/argoApplication/ArgoApplicationService.go
  pkg/argoApplication/bean/bean.go
  pkg/cluster/EphemeralConatinersService.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/application/bean/bean.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/bean.go
  pkg/terminal/terminalSesion.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4634 doc: Fixed Redirections and Broken Links
  .gitbook.yaml
  docs/README.md
  docs/hyperion/README.md
  docs/user-guide/creating-application/deployment-template/deployment.md
  docs/user-guide/creating-application/deployment-template/statefulset.md
  docs/user-guide/creating-application/docker-build-configuration.md
  docs/user-guide/global-configurations/README.md
  docs/user-guide/global-configurations/authorization/permission-groups.md
  docs/user-guide/jobs/README.md
  docs/user-guide/security-features/security-policies.md
  docs/user-guide/security-features/security-scans.md
  docs/user-guide/user-guide.md
Labels: PR:Ready-to-Review

#4675 doc: Added redirection with file type
  .gitbook.yaml
Labels: PR:Ready-to-Review

#4681 fix: nil pointer issue in manual sync api
  api/restHandler/app/pipeline/status/PipelineStatusTimelineRestHandler.go
Labels: PR:Ready-to-Review

#4678 fix: updated rbac for argo apps listing and detail fetch apis
  api/argoApplication/ArgoApplicationRestHandler.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4686 doc: Added Build Infra Doc
  docs/SUMMARY.md
  docs/user-guide/global-configurations/build-infra.md
Labels: PR:Ready-to-Review

#4685 fix: User api version for old apis
  api/auth/user/UserRestHandler.go
  api/auth/user/UserRouter.go
  api/bean/UserRequest.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserService.go
  specs/group_policy.yaml
  specs/user_policy.yaml
  wire_gen.go
Labels: PR:Ready-to-Review

#4697 doc: Updated PR Validator
  .github/semantic.yml
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#4698 misc: Changed PR template
  .github/pull_request_template.md
Labels: PR:Ready-to-Review

#4693 fix: job workflow req volume mount
  pkg/pipeline/types/Workflow.go
Labels: enhancement, PR:Ready-to-Review

#4624 feat: active inactive user phase 2
  api/auth/user/UserRestHandler.go
  api/auth/user/UserRouter.go
  api/auth/user/wire_user.go
  api/bean/UserRequest.go
  cmd/external-app/wire_gen.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserCommonService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/helper/helper.go
  pkg/auth/user/repository/RoleGroupRepository.go
  pkg/auth/user/repository/UserAuthRepository.go
  pkg/auth/user/repository/UserRepository.go
  pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
  specs/group_policy.yaml
  specs/user_policy.yaml
  wire_gen.go
Labels: PR:Ready-to-Review

#4692 fix: chart repo delete routing
  api/chartRepo/ChartRepositoryRouter.go
Labels: PR:Ready-to-Review

#4578 fix: 5xx 3.0
  api/argoApplication/wire_argoApplication.go
  api/helm-app/service/ClusterUtils.go
  api/helm-app/service/HelmAppService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
  pkg/delete/DeleteServiceExtended.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/capacity/k8sCapacityService.go
  pkg/pipeline/BuildPipelineConfigService.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/resourceQualifiers/ResourceQualifiersMappingDto.go
Labels: PR:Ready-to-Review

#4691 fix: wrong image scan execution result
  api/restHandler/ExternalCiRestHandler.go
  api/router/pubsub/ApplicationStatusHandler.go
  internal/sql/repository/security/ImageScanHistoryRepository.go
  pkg/app/AppService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/security/ImageScanService.go
Labels: PR:Ready-to-Review

#4651 feat:version upgrade for authenticator
  App.go
  cmd/external-app/externalApp.go
  go.mod
  go.sum
  vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4711 chore: nats common lib version upgrade
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/commonBean/bean.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4507 docs: Workflow + Skopeo + Approval + Image Tag at CI + Image Tag + Image Digest at CD
  docs/SUMMARY.md
  docs/user-guide/creating-application/workflow/cd-pipeline.md
  docs/user-guide/creating-application/workflow/ci-pipeline.md
  docs/user-guide/creating-application/workflow/plugins/copy-container-image.md
  docs/user-guide/deploying-application/triggering-cd.md
  docs/user-guide/global-configurations/pull-image-digest.md
Labels: PR:Ready-to-Review

#4666 feat: change deployment type from gitops to non-gitops and vice-versa for chart store apps
  Wire.go
  api/appStore/AppStoreRouter.go
  api/appStore/InstalledAppRestHandler.go
  client/argocdServer/k8sClient.go
  internal/sql/repository/app/AppRepository.go
  internal/sql/repository/pipelineConfig/PipelineRepository.go
  pkg/appStore/bean/bean.go
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/InstalledAppDeploymentTypeChangeService.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppGitOpsService.go
  pkg/appStore/util/util.go
  pkg/bean/app.go
  pkg/cluster/ClusterService.go
  pkg/pipeline/AppDeploymentTypeChangeManager.go
  util/argo/ArgoUserService.go
  util/argo/HelmUserService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4716 doc: Navigation and Scaffolding Fixes
  docs/SUMMARY.md
  docs/user-guide/creating-application/workflow/cd-pipeline.md
  docs/user-guide/creating-application/workflow/ci-build-pre-post-plugins.md
  docs/user-guide/creating-application/workflow/ci-pipeline.md
  docs/user-guide/global-configurations/README.md
  docs/user-guide/global-configurations/authorization/README.md
  docs/user-guide/plugins/README.md
  docs/user-guide/plugins/codacy.md
  docs/user-guide/plugins/copy-container-image.md
  docs/user-guide/plugins/dependency-track-maven-gradle.md
  docs/user-guide/plugins/dependency-track-nodejs.md
  docs/user-guide/plugins/dependency-track-python.md
  docs/user-guide/plugins/k6-load-testing.md
  docs/user-guide/plugins/semgrep.md
  docs/user-guide/plugins/sonarqube.md
Labels: PR:Ready-to-Review

#4724 fix: 28feb packet common bug fix
  pkg/appStore/installedApp/service/FullMode/InstalledAppDeploymentTypeChangeService.go
  pkg/appStore/util/util.go
  pkg/bean/app.go
  pkg/deployment/gitOps/git/commandManager/GitCliManager.go
Labels: enhancement, PR:Ready-to-Review

#4729 fix: review comment fixes for user defined GitOps repo url
  api/restHandler/GitOpsConfigRestHandler.go
  client/argocdServer/ArgoClientWrapperService.go
  client/argocdServer/bean/bean.go
  pkg/app/ManifestPushService.go
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
  pkg/chart/ChartService.go
  pkg/chart/bean.go
  pkg/chart/gitOpsConfig/DevtronAppGitOpsConfigService.go
  pkg/chartRepo/repository/ChartsRepository.go
  pkg/deployment/gitOps/git/GitOperationService.go
  pkg/deployment/gitOps/git/GitOpsHelper.go
  pkg/deployment/gitOps/git/GitServiceBitbucket.go
  pkg/pipeline/AppDeploymentTypeChangeManager.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  util/retryFunc/RetryFunction.go
  wire_gen.go
Labels: enhancement
