Repository devtron-labs/devtron, pull requests merged in 2024-09, with the labels that each got.

#5630 feat: plugin creation support
  api/restHandler/GlobalPluginRestHandler.go
  api/router/GlobalPluginRouter.go
  internal/util/ErrorUtil.go
  pkg/plugin/GlobalPluginService.go
  pkg/plugin/adaptor/adaptor.go
  pkg/plugin/bean/bean.go
  pkg/plugin/repository/GlobalPluginRepository.go
  pkg/plugin/utils/utils.go
Labels: PR:Ready-to-Review

#5778 chore: Revert "feat: plugin creation support"
  api/restHandler/GlobalPluginRestHandler.go
  api/router/GlobalPluginRouter.go
  internal/util/ErrorUtil.go
  pkg/plugin/GlobalPluginService.go
  pkg/plugin/adaptor/adaptor.go
  pkg/plugin/bean/bean.go
  pkg/plugin/repository/GlobalPluginRepository.go
  pkg/plugin/utils/utils.go
Labels: PR:Ready-to-Review

#5779 chore: Oss sync 2 sept 2024 oss
  .gitbook.yaml
  api/restHandler/DeploymentConfigurationRestHandler.go
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
  devtron-images.txt.source
  docs/SUMMARY.md
  docs/reference/glossary.md
  docs/setup/install/install-devtron-in-airgapped-environment.md
  docs/user-guide/creating-application/deployment-template.md
  docs/user-guide/global-configurations/README.md
  docs/user-guide/global-configurations/deployment-charts.md
  docs/user-guide/plugins/code-scan.md
  docs/user-guide/plugins/cosign.md
  docs/user-guide/plugins/crane-copy.md
  docs/user-guide/plugins/devtron-cd-trigger.md
  docs/user-guide/plugins/devtron-job-trigger.md
  docs/user-guide/plugins/docker-slim.md
  env_gen.md
  fetchAllEnv/fetchAllEnv.go
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/bean/app.go
  pkg/configDiff/DeploymentConfigurationService.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiLogService.go
  pkg/pipeline/CiService.go
  pkg/pipeline/ConfigMapService.go
  pkg/pipeline/types/CiCdConfig.go
  pkg/pipeline/types/Workflow.go
  pkg/sql/connection.go
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/servicemonitor.yaml
  scripts/sql/282_bitnami_chart_fix.down.sql
  scripts/sql/282_bitnami_chart_fix.up.sql
  scripts/sql/283_user_group.down.sql
  scripts/sql/283_user_group.up.sql
  util/helper.go
Labels: PR:Issue-verification-failed

#5781 misc: unimplemented cluster cron service
  api/cluster/wire_cluster.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/k8s/wire_k8sApp.go
  cmd/external-app/wire_gen.go
  pkg/cluster/ClusterCronService.go
  pkg/cluster/ClusterService.go
  pkg/cluster/ClusterServiceExtended.go
  pkg/k8s/capacity/k8sCapacityService.go
  util/GlobalConfig.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5783 fix: sql injection fixes
  pkg/auth/user/repository/UserAuthRepository.go
Labels: PR:Ready-to-Review

#5709 docs: Jira plugins doc (Validator + Updater)
  docs/SUMMARY.md
  docs/user-guide/plugins/jira-updater.md
  docs/user-guide/plugins/jira-validator.md
  docs/user-guide/plugins/plugin-list.md
Labels: PR:Ready-to-Review

#5789 feat: Added multiple features support in servicemonitor
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/servicemonitor.yaml
Labels: PR:Ready-to-Review

#5794 docs: added commands enable ingress during helm installation
  docs/setup/install/ingress-setup.md
Labels: PR:Ready-to-Review

#5798 doc: Revamped + Restructured Ingress Setup Doc
  docs/setup/install/ingress-setup.md
Labels: PR:Ready-to-Review

#5799 docs: modifying route in ingress doc
  docs/setup/install/ingress-setup.md
Labels: PR:Ready-to-Review

#5790 misc: cron status update refactoring
  api/cluster/EnvironmentRestHandler.go
  pkg/cluster/ClusterService.go
  pkg/cluster/EnvironmentService.go
Labels: enhancement, PR:Ready-to-Review

#5800 docs: modified the anchorlink in ingress.md
  docs/setup/install/ingress-setup.md
Labels: PR:Ready-to-Review

#5801 fix: Sql injection fix
  pkg/auth/user/repository/UserAuthRepository.go
Labels: PR:Ready-to-Review

#5724 feat: acr polling plugin support
  go.mod
  go.sum
  pkg/eventProcessor/bean/workflowEventBean.go
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
  pkg/pipeline/WebhookService.go
  pkg/workflow/dag/WorkflowDagExecutor.go
  scripts/sql/284_polling_plugin_v2.down.sql
  scripts/sql/284_polling_plugin_v2.up.sql
  util/helper.go
  vendor/github.com/argoproj/argo-cd/assets/badge.svg
  vendor/github.com/argoproj/argo-cd/assets/builtin-policy.csv
  vendor/github.com/argoproj/argo-cd/assets/model.conf
  vendor/github.com/argoproj/argo-cd/assets/swagger.json
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/LICENSE.txt
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/types/enums.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/types/errors.go
  vendor/github.com/aws/aws-sdk-go-v2/service/ecr/types/types.go
  vendor/github.com/aws/smithy-go/.gitignore
  vendor/github.com/aws/smithy-go/.travis.yml
  vendor/github.com/aws/smithy-go/CHANGELOG.md
  vendor/github.com/aws/smithy-go/CODE_OF_CONDUCT.md
  vendor/github.com/aws/smithy-go/CONTRIBUTING.md
  vendor/github.com/aws/smithy-go/LICENSE
  vendor/github.com/aws/smithy-go/Makefile
  vendor/github.com/aws/smithy-go/NOTICE
  vendor/github.com/aws/smithy-go/README.md
  vendor/github.com/aws/smithy-go/doc.go
  vendor/github.com/aws/smithy-go/document.go
  vendor/github.com/aws/smithy-go/document/doc.go
  vendor/github.com/aws/smithy-go/document/document.go
  vendor/github.com/aws/smithy-go/document/errors.go
  vendor/github.com/aws/smithy-go/errors.go
  vendor/github.com/aws/smithy-go/go_module_metadata.go
  vendor/github.com/aws/smithy-go/local-mod-replace.sh
  vendor/github.com/aws/smithy-go/modman.toml
  vendor/github.com/aws/smithy-go/properties.go
  vendor/github.com/aws/smithy-go/validation.go
  vendor/github.com/devtron-labs/common-lib/utils/registry/bean.go
  vendor/github.com/devtron-labs/common-lib/utils/registry/pluginArtifact.go
  vendor/modules.txt
Labels: PR:Issue-verification-failed

#5813 fix: Ea rbac fixes
  pkg/appStore/bean/bean.go
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  util/rbac/EnforcerUtilHelm.go
Labels: PR:Ready-to-Review

#5808 fix: scan list in global security page sql injection fix
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
Labels: PR:Ready-to-Review

#5768 feat: Argo listing change
  api/argoApplication/ArgoApplicationRestHandler.go
  api/argoApplication/wire_argoApplication.go
  api/helm-app/HelmAppRestHandler.go
  api/k8s/application/k8sApplicationRestHandler.go
  cmd/external-app/wire_gen.go
  pkg/argoApplication/ArgoApplicationService.go
  pkg/argoApplication/helper/helper.go
  pkg/argoApplication/read/ArgoApplicationReadService.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/terminal/terminalSesion.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5757 feat: Feature release v7 sql scripts
  scripts/sql/285_release_channel.down.sql
  scripts/sql/285_release_channel.up.sql
Labels: PR:Ready-to-Review

#5823 fix: app details page
  internal/sql/repository/AppListingRepository.go
Labels: PR:Ready-to-Review

#5841 chore: Custom tag for copy container image plugin (#5760)
  internal/sql/repository/CiArtifactRepository.go
  internal/sql/repository/CustomTagRepository.go
  pkg/deployment/trigger/devtronApps/PostStageTriggerService.go
  pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
  pkg/eventProcessor/bean/pluginArtifactsBean.go
  pkg/eventProcessor/bean/workflowEventBean.go
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
  pkg/pipeline/CiService.go
  pkg/pipeline/CustomTagService.go
  pkg/pipeline/PipelineStageService.go
  pkg/pipeline/pipelineStageVariableParser.go
  pkg/plugin/GlobalPluginService.go
  pkg/workflow/dag/WorkflowDagExecutor.go
  scripts/sql/286_copy_container_image_v2.down.sql
  scripts/sql/286_copy_container_image_v2.up.sql
  util/mapUtil.go
Labels: PR:Ready-to-Review

#5840 chore: migration number fix
  go.mod
  go.sum
  scripts/sql/287_alter_mandatory_plugin_policy_for_parent_plugin_id.down.sql
  scripts/sql/287_alter_mandatory_plugin_policy_for_parent_plugin_id.up.sql
Labels: PR:Ready-to-Review

#5844 fix: plugin ip variables value getting changed
  api/restHandler/app/pipeline/configure/DeploymentPipelineRestHandler.go
  pkg/pipeline/PipelineStageService.go
Labels: PR:Ready-to-Review

#5854 fix: ignore kubelink errors in server startup (#5852)
  api/helm-app/service/HelmAppService.go
  api/restHandler/DockerRegRestHandler.go
  pkg/pipeline/DockerRegistryConfig.go
  pkg/server/ServerCacheService.go
Labels: PR:Issue-verification-failed

#5804 fix: fixed user rbac flows
  api/auth/user/UserRestHandler.go
  api/bean/UserRequest.go
  cmd/external-app/wire_gen.go
  pkg/apiToken/ApiTokenService.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserCommonService.go
  pkg/auth/user/UserService.go
Labels: PR:Ready-to-Review

#5636 doc: ArgoCD + FluxCD App Listing
  docs/reference/glossary.md
  docs/user-guide/applications.md
Labels: documentation, PR:Ready-to-Review

#5850 doc: Added Special CEL Expr in Filter Condition doc
  docs/user-guide/global-configurations/filter-condition.md
Labels: documentation, PR:Ready-to-Review

#5869 fix: pg multiple rows in EA mode (cherry pick ref - #5865)
  api/helm-app/service/HelmAppService.go
  internal/sql/repository/app/AppRepository.go
  pkg/app/AppCrudOperationService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
Labels: PR:Ready-to-Review

#5863 fix: app overview panic for helm app
  api/appStore/InstalledAppRestHandler.go
Labels: PR:Ready-to-Review

#5873 fix: oss-issues-on app detail page
  internal/sql/repository/AppListingRepository.go
Labels: PR:Ready-to-Review

#5876 fix: copy container image
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
  pkg/pipeline/pipelineStageVariableParser.go
  pkg/workflow/dag/WorkflowDagExecutor.go
Labels: PR:Ready-to-Review

#5885 misc: Update CODEOWNERS
  .github/CODEOWNERS
Labels: PR:Ready-to-Review

#5890 misc: added migration to fix default image in slack notification template
  scripts/sql/288_slack_notification_template.down.sql
  scripts/sql/288_slack_notification_template.up.sql
Labels: PR:Ready-to-Review

#5903 fix: app update migration
  Wire.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/app/AppRepository.go
  pkg/app/AppCrudOperationService.go
  pkg/app/dbMigration/migration.go
  util/rbac/EnforcerUtil.go
  util/rbac/EnforcerUtilHelm.go
  wire_gen.go
Labels: PR:Ready-to-Review

#5916 fix: Packet testing fixes
  Makefile
  Wire.go
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/helm-app/HelmAppRestHandler.go
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/app/AppRepository.go
  internal/sql/repository/dockerRegistry/DockerArtifactStoreRepository.go
  pkg/app/AppCrudOperationService.go
  pkg/app/dbMigration/migration.go
  pkg/appStore/bean/bean.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
  pkg/delete/DeleteService.go
  pkg/delete/DeleteServiceFullMode.go
  util/rbac/EnforcerUtil.go
  util/rbac/EnforcerUtilHelm.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5921 fix: get with deduplicate in resource qualifier mapping
  pkg/resourceQualifiers/helper.go
Labels: PR:Issue-verification-failed

#5874 feat: Added support for templates in external secrets
  api/appbean/AppDetail.go
  api/bean/ConfigMapAndSecret.go
  api/restHandler/CoreAppRestHandler.go
  pkg/appClone/AppCloneService.go
  pkg/bean/configSecretData.go
  pkg/pipeline/ConfigMapService.go
  pkg/pipeline/bean/ConfigMapBean.go
  pkg/pipeline/history/ConfigMapHistoryService.go
  pkg/pipeline/history/bean.go
  pkg/variables/ScopedVariableCMCSManager.go
Labels: enhancement, PR:Ready-to-Review

#5920 fix: nil ptr extra env vars fix
  pkg/pipeline/CiService.go
Labels: PR:Issue-verification-failed

#5922 fix: Docker and makefile fix
  Dockerfile
  DockerfileEA
  Makefile
Labels: PR:Issue-verification-failed

#5917 fix: user flows permissions fix
  api/auth/user/UserRestHandler.go
  api/bean/UserRequest.go
  cmd/external-app/wire_gen.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/helper/helper.go
  pkg/auth/user/repository/UserAuthRepository.go
  pkg/auth/user/util/util.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5923 fix: user flows revert PR
  api/auth/user/UserRestHandler.go
  api/bean/UserRequest.go
  cmd/external-app/wire_gen.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/helper/helper.go
  pkg/auth/user/repository/UserAuthRepository.go
  pkg/auth/user/util/util.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5787 fix: Code security fixes (sql injection, sensitive data logs)
  api/restHandler/DockerRegRestHandler.go
  api/restHandler/GitProviderRestHandler.go
  api/restHandler/common/apiError.go
  client/gitSensor/GitSensorRestClient.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/AppListingRepository.go
  internal/sql/repository/app/AppRepository.go
  internal/sql/repository/bulkUpdate/BulkUpdateRepository.go
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
  internal/sql/repository/security/CveStoreRepository.go
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/discover/repository/AppStoreApplicationVersionRepository.go
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/DeploymentStatusService.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/bean/bean.go
  pkg/auth/user/repository/DefaultAuthRoleRepository.go
  pkg/auth/user/repository/RoleGroupRepository.go
  pkg/auth/user/repository/UserRepository.go
  pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
  pkg/deployment/trigger/devtronApps/PostStageTriggerService.go
  pkg/eventProcessor/out/CIPipelineEventPublishService.go
  pkg/externalLink/ExternalLinkIdentifierMappingRepository.go
  pkg/pipeline/CdHandler.go
  pkg/variables/parsers/VariableTemplateParser.go
  util/SQLUtil.go
  util/ValidatorHelper.go
  util/queryHelper.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5925 fix: nil ptr fix in copying extraEnvVars
  pkg/pipeline/CiService.go
Labels: PR:Ready-to-Review
