Repository devtron-labs/devtron, pull requests merged in 2024-10, with the labels that each got.

#5934 feat: Added Devtron CI Trigger v1.1.0
  scripts/sql/028901_019_devtron_ci_trigger_v1_1.down.sql
  scripts/sql/028901_019_devtron_ci_trigger_v1_1.up.sql
Labels: PR:Ready-to-Review

#5929 fix: update User Rbac Fixes
  api/auth/user/UserRestHandler.go
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
  cmd/external-app/wire_gen.go
  pkg/apiToken/ApiTokenService.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserCommonService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/repository/RoleGroupRepository.go
  pkg/auth/user/repository/UserAuthRepository.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#5938 misc: err handling for configmap access
  client/telemetry/TelemetryEventClient.go
Labels: PR:Ready-to-Review

#5946 fix: sync with common-lib changes
  go.mod
  go.sum
  vendor/modules.txt
Labels: dependencies, PR:Issue-verification-failed, multi-gitter

#5957 fix: modified the query for GetQueryForUserListingWithFilters
  pkg/auth/user/repository/helper/UserRepositoryQueryBuilder.go
Labels: PR:Ready-to-Review

#5964 fix: Appdetails oss nil fix rc
  pkg/argoApplication/ArgoApplicationServiceExtended.go
Labels: PR:Issue-verification-failed

#5966 fix: auth role group fix
  api/auth/user/UserRestHandler.go
  api/auth/user/util/util.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/helper/helper.go
Labels: PR:Issue-verification-failed

#5967 fix: last deployed filter fix
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
Labels: PR:Issue-verification-failed

#5968 fix: Bulk cm edit fix
  pkg/bulkAction/BulkUpdateService.go
  util/SQLUtil.go
Labels: PR:Issue-verification-failed

#5969 fix: app details oss
  internal/sql/repository/AppListingRepository.go
Labels: PR:Issue-verification-failed

#5971 fix: app status filter for not deployed
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
Labels: PR:Issue-verification-failed

#5972 fix: rollback fix
  pkg/deployment/manifest/ManifestCreationService.go
Labels: PR:Issue-verification-failed

#5974 misc: copy container image version
  pkg/pipeline/pipelineStageVariableParser.go
Labels: PR:Issue-verification-failed

#5977 fix: notification cluster filter issue
  client/events/EventBuilder.go
  client/events/EventClient.go
  pkg/app/AppService.go
  pkg/app/DeploymentEventHandler.go
  pkg/deployment/trigger/devtronApps/PostStageTriggerService.go
  pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/workflow/dag/WorkflowDagExecutor.go
Labels: PR:Issue-verification-failed

#5981 chore: Common lib update on rc20
  go.mod
  go.sum
Labels: PR:Issue-verification-failed

#5978 misc: error handling while creating github repo in case of concurrent reqs
  pkg/deployment/gitOps/git/GitServiceGithub.go
Labels: PR:Ready-to-Review

#5983 chore: Main sync develop
  api/auth/user/UserRestHandler.go
  api/auth/user/util/util.go
  client/events/EventBuilder.go
  client/events/EventClient.go
  go.mod
  go.sum
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
  pkg/app/AppService.go
  pkg/app/DeploymentEventHandler.go
  pkg/auth/user/RoleGroupService.go
  pkg/auth/user/UserService.go
  pkg/auth/user/helper/helper.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/deployment/gitOps/git/GitServiceGithub.go
  pkg/deployment/manifest/ManifestCreationService.go
  pkg/deployment/trigger/devtronApps/PostStageTriggerService.go
  pkg/deployment/trigger/devtronApps/PreStageTriggerService.go
  pkg/deployment/trigger/devtronApps/TriggerService.go
  pkg/eventProcessor/in/WorkflowEventProcessorService.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiService.go
  pkg/pipeline/pipelineStageVariableParser.go
  pkg/workflow/dag/WorkflowDagExecutor.go
  util/SQLUtil.go
Labels: PR:Issue-verification-failed

#5984 misc: isLatest field in plugin_metadata tag changed to not_null
  pkg/plugin/repository/GlobalPluginRepository.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#5987 misc: Replaced != with <> for PostgreSQL compatibility
  internal/sql/repository/helper/AppListingRepositoryQueryBuilder.go
Labels: PR:Ready-to-Review

#5989 misc: removed deployment group validation when deleting CD pipelines
  pkg/pipeline/DeploymentPipelineConfigService.go
Labels: PR:Ready-to-Review

#5991 feat: terminal role casbin policy
  scripts/casbin/10_terminal.down.sql
  scripts/casbin/10_terminal.up.sql
Labels: PR:Issue-verification-failed

#6003 fix: Config deployment history fix
  pkg/configDiff/DeploymentConfigurationService.go
  pkg/configDiff/bean/bean.go
  pkg/pipeline/history/ConfigMapHistoryService.go
Labels: PR:Issue-verification-failed

#6006 chore: Cluster terminal images migration
  scripts/sql/029800_021_cluster_terminal_images.down.sql
  scripts/sql/029800_021_cluster_terminal_images.up.sql
Labels: PR:Issue-verification-failed

#6010 fix: migration fix
  scripts/sql/029800_021_cluster_terminal_images.down.sql
  scripts/sql/029800_021_cluster_terminal_images.up.sql
Labels: PR:Issue-verification-failed

#6013 fix : multiple param of filter in helm app list
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
Labels: PR:Ready-to-Review

#6018 fix: refrence charts hotfix
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/ambassador.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/configmap.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/deployment.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/externalsecrets.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/hpa.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/ingress.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/keda-autoscaling.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/poddisruptionbudget.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/pre-sync-job.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/prometheusrules.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/secret.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/service.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/serviceaccount.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/servicemonitor.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/templates/winter-soldier.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/test_values.yaml
  scripts/devtron-reference-helm-charts/deployment-chart_4-20-0/values.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/ambassador.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/configmap.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/externalsecrets.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/hpa.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/ingress.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/keda-autoscaling.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/poddisruptionbudget.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/pre-sync-job.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/prometheusrules.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/secret.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/service.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/serviceaccount.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/servicemonitor.yaml
  scripts/devtron-reference-helm-charts/reference-chart_4-20-0/templates/winter-soldier.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/app-values.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/_helpers.tpl
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/externalsecrets.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/hpa.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/keda-autoscaling.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/service.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/servicemonitor.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/statefulset.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/templates/vertical-pod-autoscaler.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-1-0/values.yaml
Labels: PR:Issue-verification-failed

#6019 fix: Helm app list cluster filter
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
Labels: PR:Issue-verification-failed

#6016 fix: plugin getByName method error handling
  pkg/plugin/GlobalPluginService.go
Labels: PR:Ready-to-Review

#6023 chore: Rename migration seq
  scripts/sql/28901901_devtron_ci_trigger_v1_1.down.sql
  scripts/sql/28901901_devtron_ci_trigger_v1_1.up.sql
  scripts/sql/28901902_docker_lint.down.sql
  scripts/sql/28901902_docker_lint.up.sql
  scripts/sql/29001900_release_rbac.down.sql
  scripts/sql/29001900_release_rbac.up.sql
  scripts/sql/29101900_notification_settings.up.sql
  scripts/sql/29101900_notification_stettings.down.sql
  scripts/sql/29201900_helm_app_deployment_message.down.sql
  scripts/sql/29201900_helm_app_deployment_message.up.sql
  scripts/sql/29302000_artifact_uploaded_flag.down.sql
  scripts/sql/29302000_artifact_uploaded_flag.up.sql
  scripts/sql/29402000_deployment_event.down.sql
  scripts/sql/29402000_deployment_event.up.sql
  scripts/sql/29502100_refrence-chart-ref_4-19-0.down.sql
  scripts/sql/29502100_refrence-chart-ref_4-19-0.up.sql
  scripts/sql/29602100_refrence-chart-ref_4-20-0.down.sql
  scripts/sql/29602100_refrence-chart-ref_4-20-0.up.sql
  scripts/sql/29702100_deployment-chart-ref_4-20-0.down.sql
  scripts/sql/29702100_deployment-chart-ref_4-20-0.up.sql
  scripts/sql/29802100_cluster_terminal_images.down.sql
  scripts/sql/29802100_cluster_terminal_images.up.sql
Labels: PR:Issue-verification-failed

#6025 fix: Delete incorrect migration seq
  scripts/sql/28901901_devtron_ci_trigger_v1_1.down.sql
  scripts/sql/28901901_devtron_ci_trigger_v1_1.up.sql
  scripts/sql/28901902_docker_lint.down.sql
  scripts/sql/28901902_docker_lint.up.sql
  scripts/sql/29001900_release_rbac.down.sql
  scripts/sql/29001900_release_rbac.up.sql
  scripts/sql/29101900_notification_settings.up.sql
  scripts/sql/29101900_notification_stettings.down.sql
  scripts/sql/29201900_helm_app_deployment_message.down.sql
  scripts/sql/29201900_helm_app_deployment_message.up.sql
Labels: PR:Issue-verification-failed

#6026 chore: Common lib update
  go.mod
  go.sum
  pkg/plugin/GlobalPluginService.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Issue-verification-failed

#6034 fix: fix for showing inaccurate data in template/list api while fetching previous deployments list in template/list api, output shown was cartesian product of deployment_template_history and wfr
  api/bean/ConfigMapAndSecret.go
  internal/sql/repository/DeploymentTemplateRepository.go
  pkg/bean/configSecretData.go
  pkg/variables/ScopedVariableCMCSManager.go
Labels: PR:Ready-to-Review
