Repository devtron-labs/devtron, pull requests merged in 2024-01, with the labels that each got.

#4414 fix: Error code changed for resource api
  api/helm-app/HelmAppService.go
  api/restHandler/AppWorkflowRestHandler.go
  api/restHandler/app/BuildPipelineRestHandler.go
  internal/util/ErrorUtil.go
  pkg/k8s/K8sCommonService.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
Labels: PR:Ready-to-Review

#4526 fix: panic in app clone service for [linked ci, external ci, linked cd] cases
  pkg/appClone/AppCloneService.go
  pkg/pipeline/CiCdPipelineOrchestrator.go
Labels: PR:Ready-to-Review

#4499 feat: Configurable namespace for secrets in dex config
  pkg/auth/sso/SSOLoginService.go
  util/GlobalConfig.go
Labels: PR:Ready-to-Review

#4472 fix: adding new fields in resource node to identify hooks in case of helm deployment
  api/helm-app/applist.pb.go
  api/helm-app/applist.proto
Labels: PR:Ready-to-Review

#4446 fix: show deployed time for artifacts those were deployed in past
  internal/sql/repository/CiArtifactRepository.go
  pkg/pipeline/AppArtifactManager.go
Labels: PR:Ready-to-Review

#4512 doc: Created Catalog Framework Doc
  docs/SUMMARY.md
  docs/user-guide/global-configurations/catalog-framework.md
Labels: documentation, PR:Ready-to-Review

#4493 docs: Segregated SSO Docs + Added Auto-Assign Permissions Feature
  docs/SUMMARY.md
  docs/user-guide/global-configurations/authorization/permission-groups.md
  docs/user-guide/global-configurations/authorization/sso/github.md
  docs/user-guide/global-configurations/authorization/sso/gitlab.md
  docs/user-guide/global-configurations/authorization/sso/google.md
  docs/user-guide/global-configurations/authorization/sso/ldap.md
  docs/user-guide/global-configurations/authorization/sso/microsoft.md
  docs/user-guide/global-configurations/authorization/sso/oidc.md
  docs/user-guide/global-configurations/authorization/sso/openshift.md
  docs/user-guide/global-configurations/authorization/user-access.md
  docs/user-guide/global-configurations/sso-login.md
Labels: documentation, PR:Ready-to-Review

#4488 fix: error handling for trigger release
  pkg/pipeline/WorkflowDagExecutor.go
Labels: enhancement, PR:Ready-to-Review

#4498 chore: Removed unused jira and migration integration
  Wire.go
  api/appStore/chartProvider/ChartProviderRestHandler.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/deployment/DeploymentConfigRestHandler.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/restHandler/BulkUpdateRestHandler.go
  api/restHandler/ChartGroupRestHandler.go
  api/restHandler/CoreAppRestHandler.go
  api/restHandler/DeploymentGroupRestHandler.go
  api/restHandler/GitHostRestHandler.go
  api/restHandler/GitProviderRestHandler.go
  api/restHandler/GlobalCMCSRestHandler.go
  api/restHandler/ImageScanRestHandler.go
  api/restHandler/JiraRestHandler.go
  api/restHandler/MigrateDbRestHandler.go
  api/restHandler/NotificationRestHandler.go
  api/restHandler/PolicyRestHandler.go
  api/restHandler/TelemetryRestHandler.go
  api/restHandler/TestSuitRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/router/MigrateDbRouter.go
  api/router/PipelineConfigRouter.go
  api/router/ProjectManagementRouter.go
  api/router/TestSuites.go
  api/router/router.go
  api/terminal/UserTerminalAccessRestHandler.go
  client/events/EventBuilder.go
  client/events/EventClient.go
  internal/sql/repository/DbConfigRepository.go
  internal/sql/repository/JiraAccountRepository.go
  internal/sql/repository/pipelineConfig/DbMigrationConfig.go
  pkg/app/AppService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/service/InstalledAppService_test.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/auth/user/bean/bean.go
  pkg/auth/user/repository/UserAuditRepository.go
  pkg/auth/user/repository/UserRepository.go
  pkg/jira/JiraService.go
  pkg/notifier/NotificationConfigService.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/DbConfigService.go
  pkg/pipeline/DbMigrationService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/projectManagementService/jira/JiraAccountValidator.go
  pkg/projectManagementService/jira/JiraManagementService.go
  pkg/security/ImageScanService.go
  scripts/sql/210_unused_integration.up.sql
  scripts/sql/210_unused_intergration.down.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#4497 chore: App store dead code cleanup and restructuring
  DockerfileEA
  Wire.go
  api/appStore/InstalledAppRestHandler.go
  api/restHandler/ChartGroupRestHandler.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  pkg/appStore/bean/bean.go
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/chartGroup/bean.go
  pkg/appStore/chartGroup/repository/ChartGroup.go
  pkg/appStore/chartGroup/repository/ChartGroupDeployment.go
  pkg/appStore/chartGroup/repository/ChartGroupEntry.go
  pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/AppStoreDeploymentService_test.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/service/InstalledAppService_test.go
  pkg/appStore/deployment/service/Notes.go
  pkg/appStore/deployment/service/ResourceTree.go
  pkg/appStore/deployment/tool/AppStoreDeploymentArgoCdService.go
  pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
  pkg/appStore/deployment/tool/DeploymentStatusService.go
  scripts/sql/211_unused_integration.up.sql
  scripts/sql/211_unused_intergration.down.sql
  wire_gen.go
Labels: PR:Issue-verification-failed

#4530 fix: resource tree err handling
  api/restHandler/AppListingRestHandler.go
Labels: PR:Ready-to-Review

#4548 Chore: updated ci_artifact.data_source migration condition
  internal/sql/repository/CiArtifactRepository.go
  pkg/pipeline/WorkflowDagExecutor.go
Labels: enhancement

#4440 fix: CD stage trigger is not working for external CI
  api/appStore/chartProvider/ChartProviderRestHandler.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/deployment/DeploymentConfigRestHandler.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/restHandler/ChartGroupRestHandler.go
  api/restHandler/CoreAppRestHandler.go
  api/restHandler/DeploymentGroupRestHandler.go
  api/restHandler/ExternalCiRestHandler.go
  api/restHandler/GitHostRestHandler.go
  api/restHandler/GitProviderRestHandler.go
  api/restHandler/GlobalCMCSRestHandler.go
  api/restHandler/ImageScanRestHandler.go
  api/restHandler/MigrateDbRestHandler.go
  api/restHandler/NotificationRestHandler.go
  api/restHandler/PolicyRestHandler.go
  api/restHandler/TelemetryRestHandler.go
  api/restHandler/TestSuitRestHandler.go
  api/router/pubsub/CiEventHandler.go
  api/terminal/UserTerminalAccessRestHandler.go
  client/events/EventBuilder.go
  internal/sql/repository/AppListingRepository.go
  internal/sql/repository/CiArtifactRepository.go
  pkg/app/AppService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/service/InstalledAppService_test.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/auth/user/bean/bean.go
  pkg/auth/user/repository/UserAuditRepository.go
  pkg/auth/user/repository/UserRepository.go
  pkg/deploymentGroup/DeploymentGroupService.go
  pkg/notifier/NotificationConfigService.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/PipelineBuilder.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/security/ImageScanService.go
  wire_gen.go
Labels: enhancement, PR:Ready-to-Review

#4255 chore: added sql-validator in git-hub action
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#4486 feat: making pre,post,deploy triggers flows idempotent
  api/restHandler/PipelineTriggerRestHandler.go
  api/router/pubsub/ApplicationStatusHandler.go
  api/router/pubsub/CiEventHandler.go
  api/router/pubsub/GitWebhookHandler.go
  api/router/pubsub/WorkflowStatusUpdateHandler.go
  client/cron/CdApplicationStatusUpdateHandler.go
  go.mod
  go.sum
  internal/sql/repository/pipelineConfig/CdWorfkflowRepository.go
  pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/WebhookService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/sql/connection.go
  scripts/sql/215_reference_id_deploy.down.sql
  scripts/sql/215_reference_id_deploy.up.sql
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/JetStreamUtil.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/NatsClient.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/PubSubClientService.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/metrics/metrics.go
  vendor/github.com/devtron-labs/common-lib/pubsub-lib/model/PubSubClientBean.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4546 chore: panic middleware and proxy handler
  App.go
  Wire.go
  api/cluster/EnvironmentRestHandler.go
  api/helm-app/HelmAppService.go
  api/router/router.go
  client/dashboard/Config.go
  client/dashboard/DashboardRouter.go
  client/dashboard/proxy.go
  client/proxy/Proxy.go
  client/proxy/ProxyRouter.go
  client/proxy/wireset.go
  client/telemetry/TelemetryEventClient.go
  client/telemetry/TelemetryEventClientExtended.go
  cmd/external-app/externalApp.go
  go.mod
  go.sum
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/auth/sso/SSOLoginService.go
  pkg/chartRepo/ChartRepositoryService.go
  pkg/cluster/ClusterService.go
  pkg/cluster/ClusterServiceExtended.go
  pkg/cluster/ClusterService_test.go
  pkg/cluster/EnvironmentService.go
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/dockerRegistry/DockerRegistryIpsConfigService.go
  pkg/generateManifest/DeployementTemplateService.go
  pkg/generateManifest/DeployementTemplateService_test.go
  pkg/gitops/GitOpsConfigService.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/capacity/k8sCapacityService.go
  pkg/k8s/informer/K8sInformerFactory.go
  pkg/module/ModuleCacheService.go
  pkg/pipeline/BlobStorageConfigService.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/CiLogService.go
  pkg/pipeline/WorkflowService.go
  pkg/pipeline/executors/SystemWorkflowExecutor.go
  pkg/sql/connection.go
  pkg/terminal/terminalSesion.go
  util/argo/ArgoUserService.go
  vendor/github.com/devtron-labs/common-lib/constants/constants.go
  vendor/github.com/devtron-labs/common-lib/middlewares/recovery.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/bean.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#4568 fix: sql script added for putting Identifier type=0 for all null values present in generic_note
  scripts/sql/216_identifier_type_generic_note.down.sql
  scripts/sql/216_identifier_type_generic_note.up.sql
Labels: PR:Ready-to-Review

#4464 fix: 500 fixes second iteration
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/k8s/application/k8sApplicationRestHandler.go
  client/gitSensor/GitSensorGrpcClient.go
  internal/sql/repository/NotificationSettingsRepository.go
  internal/sql/repository/WebhookEventDataRepository.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/tool/gitops/AppStoreDeploymentArgoCdService.go
  pkg/chartRepo/repository/ChartRepoRepository.go
  pkg/externalLink/ExternalLinkIdentifierMappingRepository.go
  pkg/externalLink/ExternalLinkMonitoringToolRepository.go
  pkg/externalLink/ExternalLinkRepository.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/pipeline/BuildPipelineConfigService.go
Labels: PR:Ready-to-Review

#4443 feat: added posthog events for cloud provider and version
  Wire.go
  client/telemetry/TelemetryEventClient.go
  client/telemetry/TelemetryEventClientExtended.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/ProviderIdentifierService.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/bean/bean.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/alibaba.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/aws.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/azure.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/digitalOcean.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/google.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/oracle.go
  vendor/github.com/devtron-labs/common-lib/utils/k8s/K8sUtil.go
  vendor/modules.txt
  wire_gen.go
Labels: PR:Ready-to-Review

#4547 feat: introduced CASBIN_DATABASE env to make casbin db configurable
  pkg/auth/authorisation/casbin/Adapter.go
  pkg/sql/connection.go
Labels: PR:Ready-to-Review

#4577 doc: added --reuse-values in troubleshoot
  docs/FAQs/devtron-troubleshoot.md
Labels: PR:Ready-to-Review

#4537 feat: Secret viewable key enhancements in get resource api and draft api
  api/k8s/application/k8sApplicationRestHandler.go
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/k8s/K8sCommonService.go
  pkg/k8s/application/k8sApplicationService.go
  pkg/k8s/bean.go
  pkg/k8s/capacity/k8sCapacityService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/pipeline/history/ConfigMapHistoryService.go
  pkg/pipeline/history/bean.go
  specs/k8s_apis-spec.yaml
Labels: PR:Ready-to-Review

#4545 chore: code refactoring v1
  DockerfileEA
  Wire.go
  api/appStore/InstalledAppRestHandler.go
  api/appStore/chartGroup/ChartGroupRestHandler.go
  api/appStore/chartGroup/ChartGroupRouter.go
  api/restHandler/BulkUpdateRestHandler.go
  api/restHandler/GitProviderRestHandler.go
  api/restHandler/JiraRestHandler.go
  api/restHandler/MigrateDbRestHandler.go
  api/restHandler/NotificationRestHandler.go
  api/restHandler/TestSuitRestHandler.go
  api/restHandler/app/DeploymentPipelineRestHandler.go
  api/restHandler/app/PipelineConfigRestHandler.go
  api/router/MigrateDbRouter.go
  api/router/PipelineConfigRouter.go
  api/router/ProjectManagementRouter.go
  api/router/TestSuites.go
  api/router/router.go
  client/events/EventClient.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/DbConfigRepository.go
  internal/sql/repository/JiraAccountRepository.go
  internal/sql/repository/pipelineConfig/DbMigrationConfig.go
  pkg/app/AppService.go
  pkg/appStore/bean/bean.go
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/chartGroup/bean.go
  pkg/appStore/chartGroup/repository/ChartGroup.go
  pkg/appStore/chartGroup/repository/ChartGroupDeployment.go
  pkg/appStore/chartGroup/repository/ChartGroupEntry.go
  pkg/appStore/deployment/fullMode/AppStoreDeploymentFullModeService.go
  pkg/appStore/deployment/service/AppStoreDeploymentService.go
  pkg/appStore/deployment/service/AppStoreDeploymentService_test.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/service/InstalledAppService_test.go
  pkg/appStore/deployment/service/Notes.go
  pkg/appStore/deployment/service/ResourceTree.go
  pkg/appStore/deployment/tool/AppStoreDeploymentArgoCdService.go
  pkg/appStore/deployment/tool/AppStoreDeploymentHelmService.go
  pkg/appStore/deployment/tool/DeploymentStatusService.go
  pkg/jira/JiraService.go
  pkg/pipeline/CiHandler.go
  pkg/pipeline/DbConfigService.go
  pkg/pipeline/DbMigrationService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/projectManagementService/jira/JiraAccountValidator.go
  pkg/projectManagementService/jira/JiraManagementService.go
  scripts/sql/218_unused_integration.up.sql
  scripts/sql/218_unused_intergration.down.sql
  wire_gen.go
Labels: enhancement, PR:Ready-to-Review

#4586 fix: panic handling when giving empty values.yaml in custom packaged chart
  internal/util/ChartService.go
Labels: PR:Ready-to-Review

#4592 chore: added recovery in crons recovery
  Wire.go
  client/cron/CdApplicationStatusUpdateHandler.go
  client/cron/CiStatusUpdateCron.go
  client/cron/CiTriggerCron.go
  client/telemetry/TelemetryEventClient.go
  client/telemetry/TelemetryEventClientExtended.go
  cmd/external-app/wire.go
  pkg/cluster/ClusterCronService.go
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/module/ModuleCronService.go
  util/cron/CronLogger.go
  wire_gen.go
Labels: PR:Ready-to-Review

#4591 fix: implemented cache for storing cloud provider
  client/telemetry/TelemetryConfig.go
  client/telemetry/TelemetryEventClient.go
  client/telemetry/TelemetryEventClientExtended.go
  go.mod
  go.sum
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/ProviderIdentifierService.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/alibaba.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/azure.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/digitalOcean.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/google.go
  vendor/github.com/devtron-labs/common-lib/cloud-provider-identifier/providers/oracle.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#4515 feat: using image digest in deployment
  Wire.go
  cmd/external-app/wire_gen.go
  pkg/appClone/AppCloneService.go
  pkg/bean/app.go
  pkg/cluster/EnvironmentService.go
  pkg/devtronResource/bean/bean.go
  pkg/imageDigestPolicy/bean.go
  pkg/imageDigestPolicy/imageDigestPolicyService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/WorkflowDagExecutor.go
  pkg/resourceQualifiers/QualifierMappingService.go
  pkg/resourceQualifiers/ResourceQualifiersMappingDto.go
  pkg/resourceQualifiers/ResourceQualifiersMappingRepository.go
  pkg/resourceQualifiers/bean.go
  scripts/sql/219_pull_image_using_digest.down.sql
  scripts/sql/219_pull_image_using_digest.up.sql
  wire_gen.go
Labels: PR:Ready-to-Review

#4553 chore: fix for the extra [ ] in volume mount in statefulset chart
  scripts/devtron-reference-helm-charts/statefulset-chart_4-19-0/templates/statefulset.yaml
  scripts/devtron-reference-helm-charts/statefulset-chart_5-0-0/templates/statefulset.yaml
Labels: PR:Ready-to-Review

#4596 chore: App store services refactoring
  Wire.go
  api/appStore/InstalledAppRestHandler.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/appStore/deployment/wire_appStoreDeployment.go
  api/appStore/values/wire_appStoreValues.go
  api/helm-app/HelmAppRestHandler.go
  api/helm-app/service/HelmAppService.go
  api/restHandler/AppListingRestHandler.go
  api/router/pubsub/ApplicationStatusHandler.go
  client/cron/CdApplicationStatusUpdateHandler.go
  client/telemetry/TelemetryEventClient.go
  client/telemetry/TelemetryEventClientExtended.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  pkg/app/AppCrudOperationService.go
  pkg/app/AppService.go
  pkg/app/status/PipelineStatusTimelineService.go
  pkg/appStore/adapter/Adapter.go
  pkg/appStore/chartGroup/ChartGroupService.go
  pkg/appStore/deployment/service/InstalledAppService.go
  pkg/appStore/deployment/service/InstalledAppService_test.go
  pkg/appStore/installedApp/adapter/Adapter.go
  pkg/appStore/installedApp/repository/ClusterInstalledAppsRepository.go
  pkg/appStore/installedApp/repository/InstalledAppModels.go
  pkg/appStore/installedApp/repository/InstalledAppRepository.go
  pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
  pkg/appStore/installedApp/service/AppStoreDeploymentDBService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService_test.go
  pkg/appStore/installedApp/service/EAMode/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
  pkg/appStore/installedApp/service/FullMode/InstalledAppDBExtendedService.go
  pkg/appStore/installedApp/service/FullMode/deployment/DeploymentStatusService.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppArgoCdService.go
  pkg/appStore/installedApp/service/FullMode/deployment/InstalledAppGitOpsService.go
  pkg/appStore/installedApp/service/FullMode/resource/NotesService.go
  pkg/appStore/installedApp/service/FullMode/resource/ResourceTreeService.go
  pkg/appStore/installedApp/service/bean/bean.go
  pkg/appStore/installedApp/service/common/AppStoreDeploymentCommonService.go
  pkg/appStore/values/service/AppStoreValuesService.go
  pkg/cluster/ClusterServiceExtended.go
  pkg/delete/DeleteService.go
  pkg/delete/DeleteServiceExtended.go
  pkg/deployment/gitOps/wire_gitOps.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/WorkflowDagExecutor.go
  util/rbac/EnforcerUtilHelm.go
  wire_gen.go
Labels: enhancement

#4607 doc: Redirection added for old SSO doc link
  .gitbook.yaml
Labels: documentation, PR:Ready-to-Review

#4600 chore: Enhanced SonarQube Script by exposing Docker Image
  scripts/sql/220_exposing_sonarqube_image.down.sql
  scripts/sql/220_exposing_sonarqube_image.up.sql
Labels: PR:Ready-to-Review
