Repository devtron-labs/devtron, pull requests merged in 2024-11, with the labels that each got.

#6045 misc: permission access getting clubbed
  pkg/auth/user/UserCommonService.go
Labels: PR:Ready-to-Review

#6048 misc: helm rollback in case of no gitops (#6005)
  Wire.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/appStore/deployment/wire_appStoreDeployment.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  internal/util/ChartTemplateService.go
  pkg/appStore/adapter/Adapter.go
  pkg/appStore/bean/bean.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
  pkg/appStore/installedApp/service/EAMode/deployment/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deploymentTypeChange/InstalledAppDeploymentTypeChangeService.go
  pkg/appStore/installedApp/service/bean/bean.go
  pkg/appStore/installedApp/service/common/AppStoreDeploymentCommonService.go
  wire_gen.go
Labels: PR:Ready-to-Review

#6021 feat: added support for extraconfigs in app-sync and increased the job ttl to 1000
  charts/devtron/Chart.yaml
  charts/devtron/devtron-bom.yaml
  charts/devtron/templates/app-sync-job.yaml
  charts/devtron/templates/devtron.yaml
  charts/devtron/templates/grafana.yaml
  charts/devtron/templates/migrator.yaml
  charts/devtron/templates/minio.yaml
  charts/devtron/values.yaml
Labels: PR:Issue-verification-failed

#6051 fix: rollback and manifest output
  pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
  pkg/appStore/installedApp/service/FullMode/deployment/DeploymentStatusService.go
  pkg/generateManifest/DeploymentTemplateService.go
Labels: PR:Issue-verification-failed

#6055 misc: code owner modified
  .github/CODEOWNERS
Labels: PR:Ready-to-Review

#6059 misc: Main sync rc22 nov7
  .github/CODEOWNERS
Labels: PR:Ready-to-Review

#6052 release: Release candidate v0.22.0
  Wire.go
  api/appStore/deployment/AppStoreDeploymentRestHandler.go
  api/appStore/deployment/CommonDeploymentRestHandler.go
  api/appStore/deployment/wire_appStoreDeployment.go
  api/bean/AppView.go
  cmd/external-app/wire.go
  cmd/external-app/wire_gen.go
  internal/sql/repository/AppListingRepository.go
  internal/util/ChartTemplateService.go
  pkg/appStore/adapter/Adapter.go
  pkg/appStore/bean/bean.go
  pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
  pkg/appStore/installedApp/service/EAMode/InstalledAppDBService.go
  pkg/appStore/installedApp/service/EAMode/deployment/EAModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deployment/DeploymentStatusService.go
  pkg/appStore/installedApp/service/FullMode/deployment/FullModeDeploymentService.go
  pkg/appStore/installedApp/service/FullMode/deploymentTypeChange/InstalledAppDeploymentTypeChangeService.go
  pkg/appStore/installedApp/service/bean/bean.go
  pkg/appStore/installedApp/service/common/AppStoreDeploymentCommonService.go
  pkg/chartRepo/repository/ChartsRepository.go
  pkg/generateManifest/DeploymentTemplateService.go
  pkg/pipeline/CiHandler.go
  wire_gen.go
Labels: PR:Ready-to-Review

#6060 chore: Mandatory plugin policy v2.0 migration
  scripts/sql/29902300_mandatory_plugin_v2.down.sql
  scripts/sql/29902300_mandatory_plugin_v2.up.sql
Labels: enhancement, PR:Ready-to-Review

#6046 feat: added is_prod col in cluster
  api/k8s/capacity/k8sCapacityRestHandler.go
  pkg/cluster/ClusterService.go
  pkg/cluster/repository/ClusterRepository.go
  pkg/k8s/capacity/bean/bean.go
  pkg/k8s/capacity/k8sCapacityService.go
  scripts/sql/29902100_alter_cluster_table_.down.sql
  scripts/sql/29902100_alter_cluster_table_.up.sql
  scripts/sql/30002100_cluster_panel_.down.sql
  scripts/sql/30002100_cluster_panel_.up.sql
Labels: PR:Issue-verification-failed

#6061 misc: remove environment null check while getting chart via repo url
  pkg/app/AppService.go
  pkg/app/integrationTest/AppService_test.go
  pkg/eventProcessor/in/DeployedApplicationEventProcessorService.go
Labels: PR:Ready-to-Review

#6041 chore: Read service for DeploymentTemplateHistoryService and ConfigMapHistoryService
  Wire.go
  api/restHandler/app/pipeline/history/PipelineHistoryRestHandler.go
  pkg/bulkAction/BulkUpdateService.go
  pkg/chart/ChartService.go
  pkg/chartRepo/ChartRepositoryService.go
  pkg/configDiff/DeploymentConfigurationService.go
  pkg/deployment/manifest/configMapAndSecret/ConfigMapHistoryService.go
  pkg/deployment/manifest/configMapAndSecret/read/ConfigMapHistoryReadService.go
  pkg/deployment/manifest/configMapAndSecret/wire_configMapAndSecret.go
  pkg/deployment/manifest/deploymentTemplate/DeploymentTemplateHistoryService.go
  pkg/deployment/manifest/deploymentTemplate/read/DeploymentTemplateHistoryReadService.go
  pkg/deployment/manifest/deploymentTemplate/wire_deploymentTemplate.go
  pkg/deployment/manifest/wire_deployment_manifest.go
  pkg/devtronResource/history/deployment/cdPipeline/DeploymentHistoryService.go
  pkg/generateManifest/DeploymentTemplateService.go
  pkg/pipeline/ConfigMapService.go
  pkg/pipeline/DeploymentConfigService.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/pipeline/PropertiesConfig.go
  pkg/pipeline/history/ConfigMapHistoryService.go
  pkg/pipeline/history/DeployedConfigurationHistoryService.go
  pkg/pipeline/history/PipelineStrategyHistoryService.go
  pkg/pipeline/history/PrePostCdScriptHistoryService.go
  pkg/pipeline/history/adaptors/adaptor.go
  pkg/pipeline/history/bean/bean.go
  pkg/pipeline/history/mocks/ConfigMapHistoryService.go
  pkg/pipeline/history/repository/DeploymentTemplateHistoryRepository.go
  pkg/pipeline/history/wire_history.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#6082 misc: handler error while while helm deployment
  pkg/appStore/installedApp/service/AppStoreDeploymentService.go
Labels: PR:Ready-to-Review

#6097 misc: Sql query fixes
  internal/sql/repository/AppListingRepository.go
  pkg/appStore/installedApp/repository/InstalledAppVersionHistory.go
  pkg/cluster/EnvironmentService.go
  pkg/cluster/repository/EnvironmentRepository.go
  pkg/externalLink/ExternalLinkIdentifierMappingRepository.go
  pkg/pipeline/DeploymentPipelineConfigService.go
  pkg/security/policyService.go
Labels: PR:Ready-to-Review

#6086 misc: Update pr-issue-validator.yaml
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#6063 chore: refactoring image tagging reader service
  Wire.go
  api/restHandler/app/pipeline/configure/BuildPipelineRestHandler.go
  api/restHandler/app/pipeline/configure/DeploymentPipelineRestHandler.go
  api/restHandler/app/pipeline/configure/PipelineConfigRestHandler.go
  internal/sql/repository/pipelineConfig/mocks/CiPipelineRepository.go
  internal/sql/repository/pipelineConfig/mocks/PipelineRepository.go
  pkg/build/artifacts/imageTagging/ImageTaggingService.go
  pkg/build/artifacts/imageTagging/ImageTaggingService_test.go
  pkg/build/artifacts/imageTagging/read/Config.go
  pkg/build/artifacts/imageTagging/read/ImageTaggingReadService.go
  pkg/build/artifacts/imageTagging/read/mocks/ImageTaggingReadService.go
  pkg/build/artifacts/imageTagging/wire_image_tagging.go
  pkg/cluster/repository/mocks/EnvironmentRepository.go
  pkg/devtronResource/history/deployment/cdPipeline/DeploymentHistoryService.go
  pkg/pipeline/AppArtifactManager.go
  pkg/pipeline/CdHandler.go
  pkg/pipeline/CiHandler.go
  wire_gen.go
Labels: be-refactoring-read-bean

#6099 misc: Update codeowner
  .github/CODEOWNERS
Labels: PR:Ready-to-Review

#6100 chore: use certificates data when InsecureSkipTLSVerify is false for a cluster in case of external run CI
  pkg/pipeline/WorkflowService.go
Labels: PR:Ready-to-Review

#6111 chore: ciTemplateReadService fix
  pkg/pipeline/CiCdPipelineOrchestrator.go
Labels: PR:Issue-verification-failed

#6112 chore: ciTemplateReadService fix
  pkg/pipeline/CiCdPipelineOrchestrator.go
Labels: PR:Issue-verification-failed

#6113 fix: modified the build template subject
  scripts/sql/30402300_build_email_template.up.sql
Labels: PR:Issue-verification-failed

#6119 security filter fix
  internal/sql/repository/security/ImageScanDeployInfoRepository.go
Labels: PR:Issue-verification-failed

#6120 fix: modified the queries for the up and down of 300 and 304
  scripts/sql/30002300_appoval_email_template_subject_update.down.sql
  scripts/sql/30002300_appoval_email_template_subject_update.up.sql
  scripts/sql/30402300_build_email_template.down.sql
  scripts/sql/30402300_build_email_template.up.sql
Labels: PR:Issue-verification-failed

#6122 misc: Main sync devlop nov22
  pkg/pipeline/WorkflowService.go
Labels: PR:Ready-to-Review

#6130 misc: bulk update cm/cs name reference update fix
  internal/sql/repository/bulkUpdate/BulkUpdateRepository.go
Labels: PR:Ready-to-Review

#6131 misc: authenticator panic fix
  go.mod
  go.sum
  vendor/github.com/devtron-labs/authenticator/client/oidcClient.go
  vendor/github.com/devtron-labs/authenticator/oidc/oidc.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#6134 misc: Update pull_request_template.md
  .github/pull_request_template.md
Labels: PR:Ready-to-Review

#6133 fix: Update pr-issue-validator.yaml
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#6123 feat: node k8s permissions
  api/cluster/ClusterRestHandler.go
  api/k8s/application/k8sApplicationRestHandler.go
  api/k8s/capacity/k8sCapacityRestHandler.go
  api/terminal/UserTerminalAccessRestHandler.go
  cmd/external-app/wire_gen.go
  pkg/cluster/rbac/ClusterRbacService.go
  pkg/clusterTerminalAccess/UserTerminalAccessService.go
  pkg/k8s/application/bean/bean.go
  pkg/k8s/application/k8sApplicationService.go
  util/rbac/EnforcerUtil.go
  wire_gen.go
Labels: PR:Issue-verification-failed

#6137 misc: adding validation for public repo
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#6135 feat: fetch all non deprecated plugins in list
  pkg/plugin/GlobalPluginService.go
  pkg/plugin/repository/GlobalPluginRepository.go
  scripts/sql/30502300_deprecating_plugins.down.sql
  scripts/sql/30502300_deprecating_plugins.up.sql
Labels: PR:Issue-verification-failed

#6140 fix: all modules installation fix
  pkg/module/ModuleService.go
Labels: PR:Ready-to-Review

#6143 misc: adding pr validator for fork prs as gh command will not work
  .github/CODEOWNERS
  .github/workflows/pr-issue-validator.yaml
Labels: PR:Ready-to-Review

#6144 misc: updated authenticator to c3254b79e386
  go.mod
  go.sum
  vendor/github.com/devtron-labs/authenticator/middleware/AuthMiddleware.go
  vendor/modules.txt
Labels: PR:Ready-to-Review

#6145 misc: addign new plugins images
  assets/plugin-icons/ic-plugin-ansible.png
  assets/plugin-icons/ic-plugin-apply-k8s-job.png
  assets/plugin-icons/ic-plugin-bitbucket-runner-trigger.png
  assets/plugin-icons/ic-plugin-cloudanix-imagescan.png
  assets/plugin-icons/ic-plugin-codacy.png
  assets/plugin-icons/ic-plugin-container-image-exporter.png
  assets/plugin-icons/ic-plugin-copacetic.png
  assets/plugin-icons/ic-plugin-copy-container-image.png
  assets/plugin-icons/ic-plugin-cosign.png
  assets/plugin-icons/ic-plugin-crane.png
  assets/plugin-icons/ic-plugin-devtron-cd-trigger.png
  assets/plugin-icons/ic-plugin-devtron-ci-trigger.png
  assets/plugin-icons/ic-plugin-devtron-config-updater.png
  assets/plugin-icons/ic-plugin-devtron-job-trigger.png
  assets/plugin-icons/ic-plugin-dockerslim.png
  assets/plugin-icons/ic-plugin-dtrack.png
  assets/plugin-icons/ic-plugin-eks-cluster.png
  assets/plugin-icons/ic-plugin-email-notifier.png
  assets/plugin-icons/ic-plugin-gcs-bucket.png
  assets/plugin-icons/ic-plugin-github-branch-divergence-checker.png
  assets/plugin-icons/ic-plugin-github-pr-closer.png
  assets/plugin-icons/ic-plugin-github-pr-updater.png
  assets/plugin-icons/ic-plugin-github-release.png
  assets/plugin-icons/ic-plugin-gke-provisioner.png
  assets/plugin-icons/ic-plugin-golang-migrate.png
  assets/plugin-icons/ic-plugin-hadolint.png
  assets/plugin-icons/ic-plugin-jira-updater.png
  assets/plugin-icons/ic-plugin-k6-load-testing.png
  assets/plugin-icons/ic-plugin-k8s-cli.png
  assets/plugin-icons/ic-plugin-mail-master.png
  assets/plugin-icons/ic-plugin-notify-slack.png
  assets/plugin-icons/ic-plugin-notify-webhook.png
  assets/plugin-icons/ic-plugin-pull-image-from-registry.png
  assets/plugin-icons/ic-plugin-rate-limit-fix.png
  assets/plugin-icons/ic-plugin-security-scan.png
  assets/plugin-icons/ic-plugin-semgrep.png
  assets/plugin-icons/ic-plugin-servicenow.png
  assets/plugin-icons/ic-plugin-sonarqube.png
  assets/plugin-icons/ic-plugin-terraform-cli.png
  assets/plugin-icons/ic-plugin-trigger-jenkins.png
Labels: PR:Ready-to-Review

#6108 misc: refactor-plugin-images migrations
  scripts/sql/30602300_plugin_icons_update.down.sql
  scripts/sql/30602300_plugin_icons_update.up.sql
Labels: PR:Ready-to-Review
